/* eslint-disable */
/**
 * SEED SCRIPT — Dữ liệu mẫu linh kiện PC cho Build PC Compatibility Tool
 *
 * Cách chạy:
 *   cd backend-nettech
 *   pnpm ts-node -r tsconfig-paths/register src/seed/seed.ts
 *
 * Script sẽ:
 *   1. Kết nối MongoDB Atlas (đọc từ .env)
 *   2. Upsert 15 danh mục (+ Laptop Gaming/Văn phòng/Đồ họa, Máy tính bộ, Mini PC)
 *   3. Xoá các sản phẩm seed cũ (theo sku prefix "SEED-")
 *   4. Insert sản phẩm seed (100 + 30 mục laptop/PC theo filter)
 */

import 'reflect-metadata';
import mongoose from 'mongoose';
import * as dotenv from 'dotenv';
import * as path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../../.env') });

// ─── Mongoose Schemas ─────────────────────────────────────────────────────────

const categorySchema = new mongoose.Schema(
  {
    name: String,
    slug: { type: String, unique: true },
    pcBuilderVisible: { type: Boolean, default: true },
    compatibilityAttributes: { type: Array, default: [] },
    isDeleted: { type: Boolean, default: false },
  },
  { collection: 'categories', timestamps: true },
);

const productSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    brand: { type: String, required: true },
    price: { type: Number, required: true, min: 0 },
    specifications: { type: Object },
    category: { type: mongoose.Schema.Types.ObjectId, ref: 'Category', required: true },
    totalStock: { type: Number, default: 0 },
    isActive: { type: Boolean, default: true },
    description: String,
    images: [String],
    sku: { type: String, unique: true, sparse: true },
  },
  { collection: 'products', timestamps: true },
);

const CategoryModel = mongoose.model('SeedCategory', categorySchema, 'categories');
const ProductModel = mongoose.model('SeedProduct', productSchema, 'products');

// ─── Category Definitions ─────────────────────────────────────────────────────

const CATEGORIES = [
  { name: 'Laptop',    slug: 'laptop',    pcBuilderVisible: false },
  { name: 'MacBook',   slug: 'macbook',   pcBuilderVisible: false },
  { name: 'CPU',       slug: 'cpu',       pcBuilderVisible: true  },
  { name: 'VGA',       slug: 'vga',       pcBuilderVisible: true  },
  { name: 'Mainboard', slug: 'mainboard', pcBuilderVisible: true  },
  { name: 'RAM',       slug: 'ram',       pcBuilderVisible: true  },
  { name: 'SSD',       slug: 'ssd',       pcBuilderVisible: true  },
  { name: 'PSU',       slug: 'psu',       pcBuilderVisible: true  },
  { name: 'Case',      slug: 'case',      pcBuilderVisible: true  },
  { name: 'Cooler',    slug: 'cooler',    pcBuilderVisible: true  },
  { name: 'Laptop Gaming',      slug: 'laptop-gaming',      pcBuilderVisible: false },
  { name: 'Laptop văn phòng',   slug: 'laptop-van-phong',   pcBuilderVisible: false },
  { name: 'Laptop đồ họa',      slug: 'laptop-do-hoa',      pcBuilderVisible: false },
  { name: 'Máy tính bộ',        slug: 'may-tinh-bo',        pcBuilderVisible: false },
  { name: 'Mini PC',            slug: 'mini-pc',            pcBuilderVisible: false },
];

// ─── Helper: ảnh sản phẩm ─────────────────────────────────────────────────────
// Nếu truyền URL đầy đủ (http/https) → dùng trực tiếp.
// Nếu chỉ truyền tên text → tạo placeholder placehold.co (tránh bọc URL thật vào ?text=...).

function img(nameOrUrl: string): string {
  const s = nameOrUrl.trim();
  if (/^https?:\/\//i.test(s)) {
    return s;
  }
  return `https://placehold.co/600x600?text=${encodeURIComponent(s)}`;
}

// ─── Seed Product Factory ─────────────────────────────────────────────────────

function makeProducts(catIds: Record<string, mongoose.Types.ObjectId>) {
  return [

    // ══════════════════════════════════════════════════════════════════════════
    // LAPTOP — 10 sản phẩm
    // ══════════════════════════════════════════════════════════════════════════
    {
      name: 'Dell XPS 15 9530',
      brand: 'Dell',
      sku: 'SEED-LT-DELL-XPS15-9530',
      price: 35_000_000,
      category: catIds.laptop,
      totalStock: 10,
      description: 'Laptop cao cấp 15.6" OLED 3.5K. Intel Core i7-13700H, RTX 4060 8GB, 16GB DDR5, 512GB SSD.',
      images: [img('https://cdn.tgdd.vn/Products/Images/44/314837/dell-xps-15-9530-i7-71015716-thumb-600x600.jpg')],
      specifications: {
        processor: 'Intel Core i7-13700H',
        gpu: 'NVIDIA GeForce RTX 4060 8GB',
        ram: '16GB DDR5',
        storage: '512GB NVMe SSD',
        display: '15.6" OLED 3.5K (3456×2160) 60Hz',
        battery: '86Wh',
        weight: '1.86 kg',
        os: 'Windows 11 Home',
      },
    },
    {
      name: 'ASUS ROG Zephyrus G14 GA403UV',
      brand: 'ASUS',
      sku: 'SEED-LT-ROG-G14-GA403UV',
      price: 42_000_000,
      category: catIds.laptop,
      totalStock: 8,
      description: 'Gaming laptop 14" OLED 2.8K 120Hz. AMD Ryzen 9 8945HS, RTX 4060 8GB, 16GB LPDDR5X.',
      images: [img('https://bizweb.dktcdn.net/thumb/grande/100/512/769/products/s-l1600-7-de92321a-56da-4f59-a3be-c79263849ead.jpg?v=1724308419693')],
      specifications: {
        processor: 'AMD Ryzen 9 8945HS',
        gpu: 'NVIDIA GeForce RTX 4060 8GB',
        ram: '16GB LPDDR5X',
        storage: '1TB NVMe SSD',
        display: '14" OLED 2.8K (2880×1800) 120Hz',
        battery: '73Wh',
        weight: '1.49 kg',
        os: 'Windows 11 Home',
      },
    },
    {
      name: 'Lenovo ThinkPad X1 Carbon Gen 12',
      brand: 'Lenovo',
      sku: 'SEED-LT-TP-X1C-GEN12',
      price: 45_000_000,
      category: catIds.laptop,
      totalStock: 7,
      description: 'Ultrabook doanh nhân 14" IPS 2.8K. Intel Core Ultra 7 165U, 32GB LPDDR5, 1TB SSD.',
      images: [img('https://anphat.com.vn/media/lib/23-05-2024/laptop_lenovo_thinkpad_x1_carbon_gen_12_21kc008mvn_0.jpg')],
      specifications: {
        processor: 'Intel Core Ultra 7 165U',
        gpu: 'Intel Graphics',
        ram: '32GB LPDDR5',
        storage: '1TB NVMe SSD',
        display: '14" IPS 2.8K (2880×1800) 60Hz',
        battery: '57Wh',
        weight: '1.12 kg',
        os: 'Windows 11 Pro',
      },
    },
    {
      name: 'HP Spectre x360 14-ef2xxx',
      brand: 'HP',
      sku: 'SEED-LT-HP-SPECTRE-X360-14',
      price: 32_000_000,
      category: catIds.laptop,
      totalStock: 10,
      description: 'Laptop 2-in-1 cao cấp 14" OLED 2.8K. Intel Core Ultra 7 155H, 16GB LPDDR5, 1TB SSD.',
      images: [img('https://static.hungphatlaptop.com/wp-content/uploads/2024/11/HP-Spectre-X360-2-in-1-14-inch-2024-Features-04.jpeg')],
      specifications: {
        processor: 'Intel Core Ultra 7 155H',
        gpu: 'Intel Arc Graphics',
        ram: '16GB LPDDR5',
        storage: '1TB NVMe SSD',
        display: '14" OLED 2.8K (2880×1800) Touch',
        battery: '66Wh',
        weight: '1.40 kg',
        os: 'Windows 11 Home',
      },
    },
    {
      name: 'MSI Titan GT77 HX 13VH',
      brand: 'MSI',
      sku: 'SEED-LT-MSI-TITAN-GT77-13VH',
      price: 75_000_000,
      category: catIds.laptop,
      totalStock: 4,
      description: 'Gaming laptop 17.3" QHD 240Hz. Intel Core i9-13980HX, RTX 4080 12GB, 64GB DDR5.',
      images: [img('https://m.media-amazon.com/images/I/71fytrhfnmL.jpg')],
      specifications: {
        processor: 'Intel Core i9-13980HX',
        gpu: 'NVIDIA GeForce RTX 4080 12GB',
        ram: '64GB DDR5',
        storage: '2TB NVMe SSD (RAID 0)',
        display: '17.3" QHD (2560×1440) 240Hz',
        battery: '99.9Wh',
        weight: '3.3 kg',
        os: 'Windows 11 Home',
      },
    },
    {
      name: 'Razer Blade 15 (2024)',
      brand: 'Razer',
      sku: 'SEED-LT-RAZER-BLADE15-2024',
      price: 65_000_000,
      category: catIds.laptop,
      totalStock: 5,
      description: 'Gaming laptop 15.6" QHD 240Hz. Intel Core i9-14900HX, RTX 4080 12GB, 32GB DDR5.',
      images: [img('https://www.cnet.com/a/img/resize/fb151e43414d98d72c0c8ef5272e3a45f884daa5/hub/2024/01/08/8a0ba506-8801-4b08-b6b0-d56cd61ff6d8/rzer-blade-16-2024.jpg?auto=webp&width=1200')],
      specifications: {
        processor: 'Intel Core i9-14900HX',
        gpu: 'NVIDIA GeForce RTX 4080 12GB',
        ram: '32GB DDR5',
        storage: '1TB NVMe SSD',
        display: '15.6" QHD (2560×1440) 240Hz',
        battery: '82Wh',
        weight: '2.01 kg',
        os: 'Windows 11 Home',
      },
    },
    {
      name: 'Acer Predator Helios 16 PH16-72',
      brand: 'Acer',
      sku: 'SEED-LT-ACER-PH16-72',
      price: 48_000_000,
      category: catIds.laptop,
      totalStock: 8,
      description: 'Gaming laptop 16" QHD+ 240Hz. Intel Core i9-14900HX, RTX 4080 12GB, 32GB DDR5.',
      images: [img('https://laptop360.net/wp-content/uploads/2024/09/Screenshot_30.png')],
      specifications: {
        processor: 'Intel Core i9-14900HX',
        gpu: 'NVIDIA GeForce RTX 4080 12GB',
        ram: '32GB DDR5',
        storage: '1TB NVMe SSD',
        display: '16" QHD+ (2560×1600) 240Hz',
        battery: '90Wh',
        weight: '2.6 kg',
        os: 'Windows 11 Home',
      },
    },
    {
      name: 'Lenovo Legion 7i Gen 9',
      brand: 'Lenovo',
      sku: 'SEED-LT-LENOVO-LEGION7I-GEN9',
      price: 52_000_000,
      category: catIds.laptop,
      totalStock: 7,
      description: 'Gaming laptop 16" IPS 2.5K 165Hz. Intel Core i9-14900HX, RTX 4070 8GB, 32GB DDR5.',
      images: [img('https://i.pcmag.com/imagery/reviews/07meYMO4LNbrpb1yTRWpRGQ-9.fit_lim.size_1050x.jpg')],
      specifications: {
        processor: 'Intel Core i9-14900HX',
        gpu: 'NVIDIA GeForce RTX 4070 8GB',
        ram: '32GB DDR5',
        storage: '1TB NVMe SSD',
        display: '16" IPS 2.5K (2560×1600) 165Hz',
        battery: '99.9Wh',
        weight: '2.4 kg',
        os: 'Windows 11 Home',
      },
    },
    {
      name: 'ASUS Vivobook Pro 15 OLED K6500ZC',
      brand: 'ASUS',
      sku: 'SEED-LT-ASUS-VBP15-K6500ZC',
      price: 22_000_000,
      category: catIds.laptop,
      totalStock: 15,
      description: 'Laptop sáng tạo 15.6" OLED 2.8K 120Hz. Intel Core i7-12700H, RTX 3050 4GB, 16GB DDR5.',
      images: [img('https://m.media-amazon.com/images/I/716G6cD12KL._AC_UF1000,1000_QL80_.jpg')],
      specifications: {
        processor: 'Intel Core i7-12700H',
        gpu: 'NVIDIA GeForce RTX 3050 4GB',
        ram: '16GB DDR5',
        storage: '512GB NVMe SSD',
        display: '15.6" OLED 2.8K (2880×1620) 120Hz',
        battery: '70Wh',
        weight: '1.65 kg',
        os: 'Windows 11 Home',
      },
    },
    {
      name: 'Samsung Galaxy Book4 Ultra',
      brand: 'Samsung',
      sku: 'SEED-LT-SAMSUNG-GB4-ULTRA',
      price: 55_000_000,
      category: catIds.laptop,
      totalStock: 6,
      description: 'Laptop cao cấp 16" AMOLED 3K 120Hz. Intel Core Ultra 9 185H, RTX 4070 8GB, 32GB.',
      images: [img('https://bizweb.dktcdn.net/100/512/769/products/samsung-galaxy-book4.jpg?v=1715325369183')],
      specifications: {
        processor: 'Intel Core Ultra 9 185H',
        gpu: 'NVIDIA GeForce RTX 4070 8GB',
        ram: '32GB LPDDR5X',
        storage: '1TB NVMe SSD',
        display: '16" Dynamic AMOLED 3K (2880×1800) 120Hz',
        battery: '76Wh',
        weight: '1.86 kg',
        os: 'Windows 11 Home',
      },
    },

    // ══════════════════════════════════════════════════════════════════════════
    // MACBOOK — 10 sản phẩm
    // ══════════════════════════════════════════════════════════════════════════
    {
      name: 'Apple MacBook Pro 14 inch M3 Pro',
      brand: 'Apple',
      sku: 'SEED-MAC-MBP14-M3PRO',
      price: 52_000_000,
      category: catIds.macbook,
      totalStock: 10,
      description: 'MacBook Pro 14 inch chip M3 Pro. 12-core CPU, 18-core GPU, 18GB Unified Memory, 512GB SSD.',
      images: [img('https://laptopnow.vn/uploads/images/2024/06/macbook-pro-14-m3-pro-1718420240.jpg')],
      specifications: {
        chip: 'Apple M3 Pro',
        cpuCores: '12-core CPU',
        gpuCores: '18-core GPU',
        ram: '18GB Unified Memory',
        storage: '512GB SSD',
        display: '14.2" Liquid Retina XDR 3024×1964 120Hz ProMotion',
        battery: 'Up to 18 hours',
        weight: '1.61 kg',
      },
    },
    {
      name: 'Apple MacBook Pro 16 inch M3 Max',
      brand: 'Apple',
      sku: 'SEED-MAC-MBP16-M3MAX',
      price: 95_000_000,
      category: catIds.macbook,
      totalStock: 5,
      description: 'MacBook Pro 16 inch chip M3 Max. 16-core CPU, 40-core GPU, 48GB Unified Memory, 1TB SSD.',
      images: [img('https://onewaymobile.vn/upload_images/images/2024/09/14/lua-chon-phien-ban-macbook-pro-phu-hop.jpg')],
      specifications: {
        chip: 'Apple M3 Max',
        cpuCores: '16-core CPU',
        gpuCores: '40-core GPU',
        ram: '48GB Unified Memory',
        storage: '1TB SSD',
        display: '16.2" Liquid Retina XDR 3456×2234 120Hz ProMotion',
        battery: 'Up to 22 hours',
        weight: '2.14 kg',
      },
    },
    {
      name: 'Apple MacBook Air 13 inch M3',
      brand: 'Apple',
      sku: 'SEED-MAC-MBA13-M3',
      price: 28_000_000,
      category: catIds.macbook,
      totalStock: 20,
      description: 'MacBook Air 13 inch chip M3. 8-core CPU, 10-core GPU, 8GB Unified Memory, 256GB SSD.',
      images: [img('https://cohotech.vn/wp-content/uploads/2024/10/Chiec-MacBook-tot-nhat-danh-cho-hau-het-nguoi-dung-nay-lai-cang-tro-nen-hoan-hao-va-tot-hon.jpg')],
      specifications: {
        chip: 'Apple M3',
        cpuCores: '8-core CPU',
        gpuCores: '10-core GPU',
        ram: '8GB Unified Memory',
        storage: '256GB SSD',
        display: '13.6" Liquid Retina 2560×1664 60Hz',
        battery: 'Up to 18 hours',
        weight: '1.24 kg',
      },
    },
    {
      name: 'Apple MacBook Air 15 inch M3',
      brand: 'Apple',
      sku: 'SEED-MAC-MBA15-M3',
      price: 34_000_000,
      category: catIds.macbook,
      totalStock: 15,
      description: 'MacBook Air 15 inch chip M3. 8-core CPU, 10-core GPU, 8GB Unified Memory, 256GB SSD.',
      images: [img('https://cdn.tgdd.vn/News/1562806/1-1280x720.jpg')],
      specifications: {
        chip: 'Apple M3',
        cpuCores: '8-core CPU',
        gpuCores: '10-core GPU',
        ram: '8GB Unified Memory',
        storage: '256GB SSD',
        display: '15.3" Liquid Retina 2880×1864 60Hz',
        battery: 'Up to 18 hours',
        weight: '1.51 kg',
      },
    },
    {
      name: 'Apple MacBook Pro 14 inch M3',
      brand: 'Apple',
      sku: 'SEED-MAC-MBP14-M3',
      price: 40_000_000,
      category: catIds.macbook,
      totalStock: 12,
      description: 'MacBook Pro 14 inch chip M3. 8-core CPU, 10-core GPU, 8GB Unified Memory, 512GB SSD.',
      images: [img('https://onewaymobile.vn/upload_images/images/2024/10/27/macbook-pro-14-m3-pro-so-huu-gam-mau-space-black.jpeg')],
      specifications: {
        chip: 'Apple M3',
        cpuCores: '8-core CPU',
        gpuCores: '10-core GPU',
        ram: '8GB Unified Memory',
        storage: '512GB SSD',
        display: '14.2" Liquid Retina XDR 3024×1964 120Hz ProMotion',
        battery: 'Up to 22 hours',
        weight: '1.55 kg',
      },
    },
    {
      name: 'Apple MacBook Pro 16 inch M3 Pro',
      brand: 'Apple',
      sku: 'SEED-MAC-MBP16-M3PRO',
      price: 72_000_000,
      category: catIds.macbook,
      totalStock: 7,
      description: 'MacBook Pro 16 inch chip M3 Pro. 12-core CPU, 18-core GPU, 18GB Unified Memory, 512GB SSD.',
      images: [img('https://i.rtings.com/assets/products/achdBcky/apple-macbook-pro-16-m3-2023/design-medium.jpg?format=auto')],
      specifications: {
        chip: 'Apple M3 Pro',
        cpuCores: '12-core CPU',
        gpuCores: '18-core GPU',
        ram: '18GB Unified Memory',
        storage: '512GB SSD',
        display: '16.2" Liquid Retina XDR 3456×2234 120Hz ProMotion',
        battery: 'Up to 22 hours',
        weight: '2.14 kg',
      },
    },
    {
      name: 'Apple MacBook Pro 14 inch M2 Pro',
      brand: 'Apple',
      sku: 'SEED-MAC-MBP14-M2PRO',
      price: 45_000_000,
      category: catIds.macbook,
      totalStock: 8,
      description: 'MacBook Pro 14 inch chip M2 Pro. 12-core CPU, 19-core GPU, 16GB Unified Memory, 512GB SSD.',
      images: [img('https://cdn.tgdd.vn/Files/2023/03/16/1518416/112-160323-135923.jpg')],
      specifications: {
        chip: 'Apple M2 Pro',
        cpuCores: '12-core CPU',
        gpuCores: '19-core GPU',
        ram: '16GB Unified Memory',
        storage: '512GB SSD',
        display: '14.2" Liquid Retina XDR 3024×1964 120Hz ProMotion',
        battery: 'Up to 18 hours',
        weight: '1.63 kg',
      },
    },
    {
      name: 'Apple MacBook Pro 16 inch M2 Max',
      brand: 'Apple',
      sku: 'SEED-MAC-MBP16-M2MAX',
      price: 85_000_000,
      category: catIds.macbook,
      totalStock: 5,
      description: 'MacBook Pro 16 inch chip M2 Max. 12-core CPU, 38-core GPU, 32GB Unified Memory, 1TB SSD.',
      images: [img('https://zshop.vn/images/detailed/121/Apple_MacBook_Pro_16_M2_Gray_Max_oa9h-47.jpg')],
      specifications: {
        chip: 'Apple M2 Max',
        cpuCores: '12-core CPU',
        gpuCores: '38-core GPU',
        ram: '32GB Unified Memory',
        storage: '1TB SSD',
        display: '16.2" Liquid Retina XDR 3456×2234 120Hz ProMotion',
        battery: 'Up to 22 hours',
        weight: '2.15 kg',
      },
    },
    {
      name: 'Apple MacBook Air 13 inch M2',
      brand: 'Apple',
      sku: 'SEED-MAC-MBA13-M2',
      price: 23_000_000,
      category: catIds.macbook,
      totalStock: 25,
      description: 'MacBook Air 13 inch chip M2. 8-core CPU, 8-core GPU, 8GB Unified Memory, 256GB SSD.',
      images: [img('https://i.ytimg.com/vi/lZGlgU95ims/maxresdefault.jpg')],
      specifications: {
        chip: 'Apple M2',
        cpuCores: '8-core CPU',
        gpuCores: '8-core GPU',
        ram: '8GB Unified Memory',
        storage: '256GB SSD',
        display: '13.6" Liquid Retina 2560×1664 60Hz',
        battery: 'Up to 18 hours',
        weight: '1.24 kg',
      },
    },
    {
      name: 'Apple MacBook Air 15 inch M2',
      brand: 'Apple',
      sku: 'SEED-MAC-MBA15-M2',
      price: 30_000_000,
      category: catIds.macbook,
      totalStock: 18,
      description: 'MacBook Air 15 inch chip M2. 8-core CPU, 10-core GPU, 8GB Unified Memory, 256GB SSD.',
      images: [img('https://cdn.tgdd.vn/Files/2023/07/19/1538885/appleinsidercopy-190723-174643.jpg')],
      specifications: {
        chip: 'Apple M2',
        cpuCores: '8-core CPU',
        gpuCores: '10-core GPU',
        ram: '8GB Unified Memory',
        storage: '256GB SSD',
        display: '15.3" Liquid Retina 2880×1864 60Hz',
        battery: 'Up to 18 hours',
        weight: '1.51 kg',
      },
    },

    // ══════════════════════════════════════════════════════════════════════════
    // CPU — 10 sản phẩm (LGA1700 × 4, AM5 × 6)
    // ══════════════════════════════════════════════════════════════════════════
    {
      name: 'Intel Core i9-14900K',
      brand: 'Intel',
      sku: 'SEED-CPU-I9-14900K',
      price: 13_500_000,
      category: catIds.cpu,
      totalStock: 15,
      description: '24 nhân (8P+16E) / 32 luồng, boost 6.0 GHz. Flagship Intel Gen 14 cho gaming và workstation.',
      images: [img('https://hanoicomputercdn.com/media/product/77007_cpu_intel_core_i9_14900k.jpg')],
      specifications: {
        socket: 'LGA1700',
        ramType: 'DDR5',
        tdp: 125,
        cores: '24 (8P+16E)',
        threads: '32',
        baseClock: '3.2 GHz',
        boostClock: '6.0 GHz',
        cache: '36 MB L3',
        pcie: 'PCIe 5.0',
      },
    },
    {
      name: 'Intel Core i7-14700K',
      brand: 'Intel',
      sku: 'SEED-CPU-I7-14700K',
      price: 9_800_000,
      category: catIds.cpu,
      totalStock: 20,
      description: '20 nhân (8P+12E) / 28 luồng, boost 5.6 GHz. Lý tưởng cho gaming + streaming.',
      images: [img('https://laptop15.vn/wp-content/uploads/2024/04/Intel-Core-I7-14700K-2.jpg')],
      specifications: {
        socket: 'LGA1700',
        ramType: 'DDR5',
        tdp: 125,
        cores: '20 (8P+12E)',
        threads: '28',
        baseClock: '3.4 GHz',
        boostClock: '5.6 GHz',
        cache: '33 MB L3',
        pcie: 'PCIe 5.0',
      },
    },
    {
      name: 'Intel Core i9-13900K',
      brand: 'Intel',
      sku: 'SEED-CPU-I9-13900K',
      price: 11_000_000,
      category: catIds.cpu,
      totalStock: 12,
      description: '24 nhân (8P+16E) / 32 luồng, boost 5.8 GHz. Flagship Intel Gen 13 hiệu suất cao.',
      images: [img('https://laptop15.vn/wp-content/uploads/2024/04/Intel-Core-I9-14900F-1.png')],
      specifications: {
        socket: 'LGA1700',
        ramType: 'DDR5',
        tdp: 125,
        cores: '24 (8P+16E)',
        threads: '32',
        baseClock: '3.0 GHz',
        boostClock: '5.8 GHz',
        cache: '36 MB L3',
        pcie: 'PCIe 5.0',
      },
    },
    {
      name: 'Intel Core i5-14600K',
      brand: 'Intel',
      sku: 'SEED-CPU-I5-14600K',
      price: 6_800_000,
      category: catIds.cpu,
      totalStock: 28,
      description: '14 nhân (6P+8E) / 20 luồng, boost 5.3 GHz. CPU tầm trung tốt nhất Gen 14.',
      images: [img('https://kccshop.vn/media/product/6483-14600k-min.jpg')],
      specifications: {
        socket: 'LGA1700',
        ramType: 'DDR4',
        tdp: 125,
        cores: '14 (6P+8E)',
        threads: '20',
        baseClock: '3.5 GHz',
        boostClock: '5.3 GHz',
        cache: '24 MB L3',
        pcie: 'PCIe 5.0',
      },
    },
    {
      name: 'AMD Ryzen 9 7950X',
      brand: 'AMD',
      sku: 'SEED-CPU-R9-7950X',
      price: 16_200_000,
      category: catIds.cpu,
      totalStock: 10,
      description: '16 nhân / 32 luồng, boost 5.7 GHz. Flagship AMD Zen 4 cho AI, rendering và workstation.',
      images: [img('https://m.media-amazon.com/images/I/5116zdA9uyL._AC_UF894,1000_QL80_.jpg')],
      specifications: {
        socket: 'AM5',
        ramType: 'DDR5',
        tdp: 170,
        cores: '16',
        threads: '32',
        baseClock: '4.5 GHz',
        boostClock: '5.7 GHz',
        cache: '64 MB L3',
        pcie: 'PCIe 5.0',
      },
    },
    {
      name: 'AMD Ryzen 7 7800X3D',
      brand: 'AMD',
      sku: 'SEED-CPU-R7-7800X3D',
      price: 10_500_000,
      category: catIds.cpu,
      totalStock: 18,
      description: '8 nhân / 16 luồng, 3D V-Cache 96 MB. CPU gaming số 1 nền tảng AM5.',
      images: [img('https://product.hstatic.net/200000722513/product/ryzen-7-7800x3d-600x600_30d6f05d43524a6c950830a366e4f4eb_2fb2daf9ef7d4faf92f0b1ed1612b1a0.png')],
      specifications: {
        socket: 'AM5',
        ramType: 'DDR5',
        tdp: 120,
        cores: '8',
        threads: '16',
        baseClock: '4.5 GHz',
        boostClock: '5.0 GHz',
        cache: '96 MB L3 (3D V-Cache)',
        pcie: 'PCIe 5.0',
      },
    },
    {
      name: 'AMD Ryzen 5 7600X',
      brand: 'AMD',
      sku: 'SEED-CPU-R5-7600X',
      price: 5_900_000,
      category: catIds.cpu,
      totalStock: 25,
      description: '6 nhân / 12 luồng, boost 5.3 GHz. CPU tầm trung AM5 tiết kiệm điện.',
      images: [img('https://product.hstatic.net/200000722513/product/ryzen_5_-_1_be51e69b02cf4ed78a758a6337e56a27_ae6fad038dff4fa985e2e4b86abc8d85_master.jpg')],
      specifications: {
        socket: 'AM5',
        ramType: 'DDR5',
        tdp: 105,
        cores: '6',
        threads: '12',
        baseClock: '4.7 GHz',
        boostClock: '5.3 GHz',
        cache: '32 MB L3',
        pcie: 'PCIe 5.0',
      },
    },
    {
      name: 'AMD Ryzen 9 9900X',
      brand: 'AMD',
      sku: 'SEED-CPU-R9-9900X',
      price: 14_500_000,
      category: catIds.cpu,
      totalStock: 8,
      description: '12 nhân / 24 luồng, boost 5.6 GHz. Thế hệ Zen 5 mới nhất cho workstation.',
      images: [img('https://product.hstatic.net/200000420363/product/_new_-anh-sp-web-recovered_828fbd6df8ca477e856f1e64d37aab89_master.png')],
      specifications: {
        socket: 'AM5',
        ramType: 'DDR5',
        tdp: 120,
        cores: '12',
        threads: '24',
        baseClock: '4.4 GHz',
        boostClock: '5.6 GHz',
        cache: '64 MB L3',
        pcie: 'PCIe 5.0',
      },
    },
    {
      name: 'AMD Ryzen 7 9700X',
      brand: 'AMD',
      sku: 'SEED-CPU-R7-9700X',
      price: 9_200_000,
      category: catIds.cpu,
      totalStock: 15,
      description: '8 nhân / 16 luồng, boost 5.5 GHz. Zen 5 hiệu quả cao, TDP thấp 65W.',
      images: [img('https://anphat.com.vn/media/product/49674_cpu_amd_ryzen_7_9700x.jpg')],
      specifications: {
        socket: 'AM5',
        ramType: 'DDR5',
        tdp: 65,
        cores: '8',
        threads: '16',
        baseClock: '3.8 GHz',
        boostClock: '5.5 GHz',
        cache: '32 MB L3',
        pcie: 'PCIe 5.0',
      },
    },
    {
      name: 'AMD Ryzen 5 9600X',
      brand: 'AMD',
      sku: 'SEED-CPU-R5-9600X',
      price: 6_500_000,
      category: catIds.cpu,
      totalStock: 22,
      description: '6 nhân / 12 luồng, boost 5.4 GHz. Zen 5 tầm trung, IPC vượt trội thế hệ trước.',
      images: [img('https://product.hstatic.net/200000722513/product/ryzen_5_-_1_be51e69b02cf4ed78a758a6337e56a27_ae6fad038dff4fa985e2e4b86abc8d85_master.jpg')],
      specifications: {
        socket: 'AM5',
        ramType: 'DDR5',
        tdp: 65,
        cores: '6',
        threads: '12',
        baseClock: '3.9 GHz',
        boostClock: '5.4 GHz',
        cache: '32 MB L3',
        pcie: 'PCIe 5.0',
      },
    },

    // ══════════════════════════════════════════════════════════════════════════
    // VGA — 10 sản phẩm
    // ══════════════════════════════════════════════════════════════════════════
    {
      name: 'NVIDIA GeForce RTX 4090 24GB',
      brand: 'NVIDIA',
      sku: 'SEED-VGA-RTX4090',
      price: 42_000_000,
      category: catIds.vga,
      totalStock: 5,
      description: 'Card đồ hoạ flagship Ada Lovelace. 24GB GDDR6X. Hiệu năng 4K gaming & AI vô đối.',
      images: [img('https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ada/rtx-4090/geforce-ada-4090-web-og-1200x630.jpg')],
      specifications: {
        length: 336,
        tdp: 450,
        vram: '24GB GDDR6X',
        boostClock: '2520 MHz',
        powerConnectors: '1× 16-pin (3× 8-pin adapter)',
        outputs: 'HDMI 2.1, 3× DP 1.4a',
        pcie: 'PCIe 4.0 x16',
      },
    },
    {
      name: 'NVIDIA GeForce RTX 4080 Super 16GB',
      brand: 'NVIDIA',
      sku: 'SEED-VGA-RTX4080S',
      price: 30_000_000,
      category: catIds.vga,
      totalStock: 8,
      description: 'RTX 4080 Super. 16GB GDDR6X. 4K gaming cao cấp, hiệu năng hơn RTX 4080 gốc.',
      images: [img('https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ada/rtx-4080/geforce-rtx-4080-super-og-1200x630.jpg')],
      specifications: {
        length: 310,
        tdp: 320,
        vram: '16GB GDDR6X',
        boostClock: '2550 MHz',
        powerConnectors: '1× 16-pin',
        outputs: 'HDMI 2.1, 3× DP 1.4a',
        pcie: 'PCIe 4.0 x16',
      },
    },
    {
      name: 'NVIDIA GeForce RTX 4070 Ti Super 16GB',
      brand: 'NVIDIA',
      sku: 'SEED-VGA-RTX4070TIS',
      price: 23_000_000,
      category: catIds.vga,
      totalStock: 12,
      description: 'RTX 4070 Ti Super. 16GB GDDR6X. 1440p/4K gaming hiệu năng cao.',
      images: [img('https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/graphic-cards/40-series/rtx-4070-4070ti/geforce-rtx-4070-super-og-1200x630.jpg')],
      specifications: {
        length: 285,
        tdp: 285,
        vram: '16GB GDDR6X',
        boostClock: '2610 MHz',
        powerConnectors: '3× 8-pin',
        outputs: 'HDMI 2.1, 3× DP 1.4a',
        pcie: 'PCIe 4.0 x16',
      },
    },
    {
      name: 'NVIDIA GeForce RTX 4070 Super 12GB',
      brand: 'NVIDIA',
      sku: 'SEED-VGA-RTX4070S',
      price: 18_500_000,
      category: catIds.vga,
      totalStock: 15,
      description: 'RTX 4070 Super. 12GB GDDR6X. Cân bằng hoàn hảo giữa hiệu năng và giá cả cho 1440p.',
      images: [img('https://images-na.ssl-images-amazon.com/images/I/61enwbiPPkL.jpg')],
      specifications: {
        length: 267,
        tdp: 220,
        vram: '12GB GDDR6X',
        boostClock: '2475 MHz',
        powerConnectors: '3× 8-pin',
        outputs: 'HDMI 2.1, 3× DP 1.4a',
        pcie: 'PCIe 4.0 x16',
      },
    },
    {
      name: 'NVIDIA GeForce RTX 4060 Ti 16GB',
      brand: 'NVIDIA',
      sku: 'SEED-VGA-RTX4060TI16G',
      price: 12_500_000,
      category: catIds.vga,
      totalStock: 18,
      description: 'RTX 4060 Ti 16GB GDDR6. Tầm trung cao với VRAM lớn cho 1440p gaming.',
      images: [img('https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ada/rtx-4060-4060ti/geforce-rtx-4060-ti-og-1200x630.jpg')],
      specifications: {
        length: 240,
        tdp: 165,
        vram: '16GB GDDR6',
        boostClock: '2535 MHz',
        powerConnectors: '1× 16-pin',
        outputs: 'HDMI 2.1, 3× DP 1.4a',
        pcie: 'PCIe 4.0 x16',
      },
    },
    {
      name: 'NVIDIA GeForce RTX 4060 8GB',
      brand: 'NVIDIA',
      sku: 'SEED-VGA-RTX4060',
      price: 8_500_000,
      category: catIds.vga,
      totalStock: 25,
      description: 'RTX 4060. 8GB GDDR6. GPU 1080p hiệu năng tốt, tiêu thụ điện cực thấp 115W.',
      images: [img('https://cdn.hstatic.net/files/200000722513/file/vga-rtx-4060-2.jpg')],
      specifications: {
        length: 240,
        tdp: 115,
        vram: '8GB GDDR6',
        boostClock: '2460 MHz',
        powerConnectors: '1× 16-pin',
        outputs: 'HDMI 2.1, 3× DP 1.4a',
        pcie: 'PCIe 4.0 x16',
      },
    },
    {
      name: 'AMD Radeon RX 7900 XTX 24GB',
      brand: 'AMD',
      sku: 'SEED-VGA-RX7900XTX',
      price: 28_000_000,
      category: catIds.vga,
      totalStock: 7,
      description: 'Radeon RX 7900 XTX. 24GB GDDR6. Flagship AMD RDNA 3, đối thủ của RTX 4080.',
      images: [img('https://anphatcom.vn/wp-content/uploads/2023/05/screenshot2023-02-06112720.png')],
      specifications: {
        length: 287,
        tdp: 355,
        vram: '24GB GDDR6',
        boostClock: '2500 MHz',
        powerConnectors: '2× 8-pin',
        outputs: 'HDMI 2.1, 2× DP 2.1',
        pcie: 'PCIe 4.0 x16',
      },
    },
    {
      name: 'AMD Radeon RX 7800 XT 16GB',
      brand: 'AMD',
      sku: 'SEED-VGA-RX7800XT',
      price: 14_000_000,
      category: catIds.vga,
      totalStock: 14,
      description: 'Radeon RX 7800 XT. 16GB GDDR6. Lựa chọn tốt nhất cho 1440p gaming của AMD.',
      images: [img('https://bizweb.dktcdn.net/100/329/122/products/vga-sapphire-nitro-plus-radeon-rx-7800-xt-gaming-oc-16g-gddr6-1.jpg?v=1743639396283')],
      specifications: {
        length: 267,
        tdp: 263,
        vram: '16GB GDDR6',
        boostClock: '2430 MHz',
        powerConnectors: '2× 8-pin',
        outputs: 'HDMI 2.1, 3× DP 2.1',
        pcie: 'PCIe 4.0 x16',
      },
    },
    {
      name: 'AMD Radeon RX 7700 XT 12GB',
      brand: 'AMD',
      sku: 'SEED-VGA-RX7700XT',
      price: 10_500_000,
      category: catIds.vga,
      totalStock: 18,
      description: 'Radeon RX 7700 XT. 12GB GDDR6. GPU tầm trung mạnh cho 1440p gaming.',
      images: [img('https://m.media-amazon.com/images/I/71NaZ7Z7VJL._AC_SL1500_.jpg')],
      specifications: {
        length: 251,
        tdp: 245,
        vram: '12GB GDDR6',
        boostClock: '2599 MHz',
        powerConnectors: '2× 8-pin',
        outputs: 'HDMI 2.1, 3× DP 2.1',
        pcie: 'PCIe 4.0 x16',
      },
    },
    {
      name: 'AMD Radeon RX 7600 8GB',
      brand: 'AMD',
      sku: 'SEED-VGA-RX7600',
      price: 6_800_000,
      category: catIds.vga,
      totalStock: 22,
      description: 'Radeon RX 7600. 8GB GDDR6. GPU 1080p giá tốt với hiệu năng RDNA 3.',
      images: [img('https://songphuong.vn/Content/uploads/2023/05/VGA-MSI-RX-7600-MECH-2X-CLASSIC-8G-OC-songphuong.vn-02.jpg')],
      specifications: {
        length: 203,
        tdp: 165,
        vram: '8GB GDDR6',
        boostClock: '2655 MHz',
        powerConnectors: '1× 8-pin',
        outputs: 'HDMI 2.1, 3× DP 2.1',
        pcie: 'PCIe 4.0 x8',
      },
    },

    // ══════════════════════════════════════════════════════════════════════════
    // MAINBOARD — 10 sản phẩm (LGA1700 × 4, AM5 × 4, LGA1700 DDR4 × 2)
    // ══════════════════════════════════════════════════════════════════════════
    {
      name: 'ASUS ROG MAXIMUS Z790 Hero',
      brand: 'ASUS',
      sku: 'SEED-MB-ROG-Z790-HERO',
      price: 18_500_000,
      category: catIds.mainboard,
      totalStock: 8,
      description: 'Bo mạch Z790 cao cấp cho Intel Gen 12/13/14. DDR5, WiFi 6E, Thunderbolt 4.',
      images: [img('https://product.hstatic.net/1000333506/product/s-rog-maximus-z790-hero-ddr5-4_239304ae40a4445d85dee5684c96dd03_grande_3ccebd17fac0403dbed13039cbca7560.jpg')],
      specifications: {
        socket: 'LGA1700',
        ramType: 'DDR5',
        formFactor: 'ATX',
        tdp: 20,
        maxRamSpeed: '7800 MHz',
        ramSlots: '4',
        pcie: 'PCIe 5.0 x16',
        m2Slots: '5',
        usb: 'USB 3.2 Gen 2x2, Thunderbolt 4',
      },
    },
    {
      name: 'ASUS ROG Strix Z790-E Gaming WiFi',
      brand: 'ASUS',
      sku: 'SEED-MB-ROG-Z790E-GAMING',
      price: 12_000_000,
      category: catIds.mainboard,
      totalStock: 10,
      description: 'Bo mạch Z790 gaming cho Intel Gen 12/13/14. DDR5, WiFi 6E, PCIe 5.0.',
      images: [img('https://product.hstatic.net/1000333506/product/rog-strix-z790-e-gaming-wifi-01_501a0bef26b7403fa0b3c85a2a31ae00_eaeb562cfd1c427cb586afdddb5becda.png')],
      specifications: {
        socket: 'LGA1700',
        ramType: 'DDR5',
        formFactor: 'ATX',
        tdp: 18,
        maxRamSpeed: '7200 MHz',
        ramSlots: '4',
        pcie: 'PCIe 5.0 x16',
        m2Slots: '4',
        usb: 'USB 3.2 Gen 2x2',
      },
    },
    {
      name: 'Gigabyte B760 AORUS Elite AX DDR4',
      brand: 'Gigabyte',
      sku: 'SEED-MB-B760-AORUS-DDR4',
      price: 5_800_000,
      category: catIds.mainboard,
      totalStock: 20,
      description: 'Bo mạch B760 tầm trung cho Intel Gen 12/13/14. Hỗ trợ DDR4, WiFi 6.',
      images: [img('https://www.alktech.co/hubfs/Gigabyte%20B760%20AORUS%20ELITE%20DDR4/Aesthetics%20(2).jpg')],
      specifications: {
        socket: 'LGA1700',
        ramType: 'DDR4',
        formFactor: 'ATX',
        tdp: 15,
        maxRamSpeed: '5333 MHz',
        ramSlots: '4',
        pcie: 'PCIe 4.0 x16',
        m2Slots: '3',
        usb: 'USB 3.2 Gen 2',
      },
    },
    {
      name: 'MSI MAG B760M Mortar WiFi DDR4',
      brand: 'MSI',
      sku: 'SEED-MB-B760M-MORTAR-DDR4',
      price: 4_200_000,
      category: catIds.mainboard,
      totalStock: 25,
      description: 'Bo mạch B760M micro-ATX cho Intel Gen 12/13/14. DDR4, WiFi 6, form nhỏ gọn.',
      images: [img('https://product.hstatic.net/200000837185/product/mainboard-msi-mag-b760m-mortar-wifi-ddr4-_-socket-intel-lga-1700-3okrq_398457f6f30b47fcb227ec04be78b3cf_master.jpg')],
      specifications: {
        socket: 'LGA1700',
        ramType: 'DDR4',
        formFactor: 'm-ATX',
        tdp: 12,
        maxRamSpeed: '5200 MHz',
        ramSlots: '4',
        pcie: 'PCIe 4.0 x16',
        m2Slots: '2',
        usb: 'USB 3.2 Gen 2',
      },
    },
    {
      name: 'MSI MEG X670E ACE',
      brand: 'MSI',
      sku: 'SEED-MB-X670E-ACE',
      price: 15_000_000,
      category: catIds.mainboard,
      totalStock: 10,
      description: 'Bo mạch X670E flagship cho AMD AM5. DDR5, PCIe 5.0 x2, WiFi 6E.',
      images: [img('https://azaudio.vn/wp-content/uploads/2024/01/msi-meg-x670e-ace-8.jpg')],
      specifications: {
        socket: 'AM5',
        ramType: 'DDR5',
        formFactor: 'ATX',
        tdp: 20,
        maxRamSpeed: '7200 MHz',
        ramSlots: '4',
        pcie: 'PCIe 5.0 x16',
        m2Slots: '4',
        usb: 'USB 3.2 Gen 2x2',
      },
    },
    {
      name: 'Gigabyte X670E AORUS Master',
      brand: 'Gigabyte',
      sku: 'SEED-MB-X670E-AORUS-MASTER',
      price: 13_500_000,
      category: catIds.mainboard,
      totalStock: 8,
      description: 'Bo mạch X670E cao cấp cho AM5. DDR5, PCIe 5.0, WiFi 6E, 10G LAN.',
      images: [img('https://product.hstatic.net/1000333506/product/9762_e503f7d296a1bb1fd0366289e6436817_2c6ff0e639364da5b32f2c22bd2fb3de_cfdc4381a77e4085b4892f8a1d742bc5.png')],
      specifications: {
        socket: 'AM5',
        ramType: 'DDR5',
        formFactor: 'ATX',
        tdp: 18,
        maxRamSpeed: '6666 MHz',
        ramSlots: '4',
        pcie: 'PCIe 5.0 x16',
        m2Slots: '4',
        usb: 'USB 3.2 Gen 2x2',
      },
    },
    {
      name: 'ASUS TUF Gaming B650-Plus WiFi',
      brand: 'ASUS',
      sku: 'SEED-MB-B650-TUF-PLUS',
      price: 6_500_000,
      category: catIds.mainboard,
      totalStock: 22,
      description: 'Bo mạch B650 tầm trung cho AM5. DDR5, WiFi 6, PCIe 5.0 NVMe.',
      images: [img('https://nvs.tn-cdn.net/2023/07/mainboard-asus-tuf-gaming-b650-plus-wifi-8.webp')],
      specifications: {
        socket: 'AM5',
        ramType: 'DDR5',
        formFactor: 'ATX',
        tdp: 15,
        maxRamSpeed: '6400 MHz',
        ramSlots: '4',
        pcie: 'PCIe 4.0 x16',
        m2Slots: '3',
        usb: 'USB 3.2 Gen 2',
      },
    },
    {
      name: 'ASUS ProArt X670E-Creator WiFi',
      brand: 'ASUS',
      sku: 'SEED-MB-X670E-PROART',
      price: 11_000_000,
      category: catIds.mainboard,
      totalStock: 6,
      description: 'Bo mạch X670E dành cho creator trên AM5. DDR5, Thunderbolt 4, 10G LAN, WiFi 6E.',
      images: [img('https://bizweb.dktcdn.net/thumb/1024x1024/100/446/096/products/maytechvn-mainboard-asus-proart-x670e-creator-wifi-ddr5-003.jpg?v=1717569480937')],
      specifications: {
        socket: 'AM5',
        ramType: 'DDR5',
        formFactor: 'ATX',
        tdp: 18,
        maxRamSpeed: '6800 MHz',
        ramSlots: '4',
        pcie: 'PCIe 5.0 x16',
        m2Slots: '4',
        usb: 'USB 3.2 Gen 2x2, Thunderbolt 4',
      },
    },
    {
      name: 'MSI MAG B650M Mortar WiFi',
      brand: 'MSI',
      sku: 'SEED-MB-B650M-MORTAR-WIFI',
      price: 4_800_000,
      category: catIds.mainboard,
      totalStock: 18,
      description: 'Bo mạch B650M micro-ATX cho AM5. DDR5, WiFi 6, form factor nhỏ gọn.',
      images: [img('https://product.hstatic.net/1000333506/product/mainboard-msi-mag-b650m-mortar-wifi-3-songphuong.vn__fd3320dfd71244ca9279962a6b9d391a_1024x1024.jpg')],
      specifications: {
        socket: 'AM5',
        ramType: 'DDR5',
        formFactor: 'm-ATX',
        tdp: 12,
        maxRamSpeed: '6400 MHz',
        ramSlots: '4',
        pcie: 'PCIe 4.0 x16',
        m2Slots: '2',
        usb: 'USB 3.2 Gen 2',
      },
    },
    {
      name: 'Gigabyte B650 AORUS Elite AX',
      brand: 'Gigabyte',
      sku: 'SEED-MB-B650-AORUS-ELITE-AX',
      price: 5_500_000,
      category: catIds.mainboard,
      totalStock: 20,
      description: 'Bo mạch B650 tầm trung cho AM5. DDR5, WiFi 6E, PCIe 5.0 M.2.',
      images: [img('https://phucanhcdn.com/media/lib/11-02-2025/anh-chan-trang-hieu-thang-2-17-1.jpg')],
      specifications: {
        socket: 'AM5',
        ramType: 'DDR5',
        formFactor: 'ATX',
        tdp: 14,
        maxRamSpeed: '6400 MHz',
        ramSlots: '4',
        pcie: 'PCIe 4.0 x16',
        m2Slots: '3',
        usb: 'USB 3.2 Gen 2',
      },
    },

    // ══════════════════════════════════════════════════════════════════════════
    // RAM — 10 sản phẩm (DDR5 × 6, DDR4 × 4)
    // ══════════════════════════════════════════════════════════════════════════
    {
      name: 'G.Skill Trident Z5 RGB 32GB DDR5-6000',
      brand: 'G.Skill',
      sku: 'SEED-RAM-GS-TZ5-32G-6000',
      price: 3_800_000,
      category: catIds.ram,
      totalStock: 30,
      description: 'Kit DDR5 32GB (2×16GB) 6000 MHz CL30. RGB đẹp, hiệu năng cao.',
      images: [img('https://product.hstatic.net/200000722513/product/z51_5fd17076678d4f5b8bdb7d1d9833c578_d741c129305e401aa8e9f1740c10a5d4.png')],
      specifications: {
        ramType: 'DDR5',
        tdp: 6,
        capacity: '32GB (2×16GB)',
        speed: '6000 MHz',
        latency: 'CL30',
        voltage: '1.35V',
      },
    },
    {
      name: 'Corsair Dominator Titanium 64GB DDR5-6400',
      brand: 'Corsair',
      sku: 'SEED-RAM-COR-DOM-64G-6400',
      price: 8_200_000,
      category: catIds.ram,
      totalStock: 12,
      description: 'Kit DDR5 64GB (2×32GB) 6400 MHz CL32. Hiệu suất đỉnh cho workstation.',
      images: [img('https://bizweb.dktcdn.net/thumb/grande/100/329/122/products/ram-pc-corsair-dominator-titanium-3.jpg?v=1695096496313')],
      specifications: {
        ramType: 'DDR5',
        tdp: 7,
        capacity: '64GB (2×32GB)',
        speed: '6400 MHz',
        latency: 'CL32',
        voltage: '1.40V',
      },
    },
    {
      name: 'Crucial Pro 32GB DDR5-5600',
      brand: 'Crucial',
      sku: 'SEED-RAM-CRU-PRO-32G-5600',
      price: 2_600_000,
      category: catIds.ram,
      totalStock: 40,
      description: 'Kit DDR5 32GB (2×16GB) 5600 MHz CL46. Giải pháp DDR5 tầm trung giá tốt.',
      images: [img('https://5sc.vn/wp-content/uploads/2023/07/Crucial-DDR5-Pro-UDIMM-Kit-Hero-Image-03.png')],
      specifications: {
        ramType: 'DDR5',
        tdp: 5,
        capacity: '32GB (2×16GB)',
        speed: '5600 MHz',
        latency: 'CL46',
        voltage: '1.10V',
      },
    },
    {
      name: 'G.Skill Trident Z5 Neo 32GB DDR5-6000',
      brand: 'G.Skill',
      sku: 'SEED-RAM-GS-TZ5NEO-32G-6000',
      price: 4_200_000,
      category: catIds.ram,
      totalStock: 20,
      description: 'Kit DDR5 32GB (2×16GB) 6000 MHz CL30. Tối ưu cho nền tảng AMD AM5 EXPO.',
      images: [img('https://bizweb.dktcdn.net/thumb/1024x1024/100/329/122/products/ram-pc-g-skill-trident-z5-neo-rgb-32gb-6000mhz-ddr5-16gbx2-f5-6000j3636f16gx2-tz5nr-1.jpg?v=1751994036393')],
      specifications: {
        ramType: 'DDR5',
        tdp: 6,
        capacity: '32GB (2×16GB)',
        speed: '6000 MHz',
        latency: 'CL30',
        voltage: '1.35V',
      },
    },
    {
      name: 'Kingston Fury Beast 16GB DDR5-5200',
      brand: 'Kingston',
      sku: 'SEED-RAM-KNG-FURY-16G-5200',
      price: 1_800_000,
      category: catIds.ram,
      totalStock: 45,
      description: 'Kit DDR5 16GB (2×8GB) 5200 MHz CL40. Entry-level DDR5 phổ biến nhất.',
      images: [img('https://nguyencongpc.vn/media/lib/21-03-2023/kitramkingstonfurybeastrgb16gb2x8gbbus5200ddr51.jpeg')],
      specifications: {
        ramType: 'DDR5',
        tdp: 4,
        capacity: '16GB (2×8GB)',
        speed: '5200 MHz',
        latency: 'CL40',
        voltage: '1.10V',
      },
    },
    {
      name: 'Corsair Vengeance RGB 32GB DDR5-5600',
      brand: 'Corsair',
      sku: 'SEED-RAM-COR-VNG-32G-5600',
      price: 3_200_000,
      category: catIds.ram,
      totalStock: 28,
      description: 'Kit DDR5 32GB (2×16GB) 5600 MHz CL36. RGB đẹp, giá tốt.',
      images: [img('https://bizweb.dktcdn.net/100/329/122/products/ram-pc-corsair-vengeance-rgb-white-32gb-5600mhz-ddr5-2x16gb-cmh32gx5m2b5600c36w-f8b29204-9089-4e36-b4b1-efa51a89e9cc.jpg?v=1758522708657')],
      specifications: {
        ramType: 'DDR5',
        tdp: 5,
        capacity: '32GB (2×16GB)',
        speed: '5600 MHz',
        latency: 'CL36',
        voltage: '1.25V',
      },
    },
    {
      name: 'Kingston Fury Beast 32GB DDR4-3600',
      brand: 'Kingston',
      sku: 'SEED-RAM-KNG-FURY-32G-3600',
      price: 1_900_000,
      category: catIds.ram,
      totalStock: 35,
      description: 'Kit DDR4 32GB (2×16GB) 3600 MHz CL18. Chuẩn vàng cho nền tảng DDR4.',
      images: [img('https://nguyencongpc.vn/media/product/22192-ram-desktop-kingston-fury-beast-rgb-1.jpg')],
      specifications: {
        ramType: 'DDR4',
        tdp: 4,
        capacity: '32GB (2×16GB)',
        speed: '3600 MHz',
        latency: 'CL18',
        voltage: '1.35V',
      },
    },
    {
      name: 'G.Skill Ripjaws V 32GB DDR4-3200',
      brand: 'G.Skill',
      sku: 'SEED-RAM-GS-RJV-32G-3200',
      price: 1_600_000,
      category: catIds.ram,
      totalStock: 40,
      description: 'Kit DDR4 32GB (2×16GB) 3200 MHz CL16. Cổ điển tin cậy, giá cả phải chăng.',
      images: [img('https://product.hstatic.net/200000456405/product/2_9a2c1c770fb147d8a42d646965392e1e.png')],
      specifications: {
        ramType: 'DDR4',
        tdp: 4,
        capacity: '32GB (2×16GB)',
        speed: '3200 MHz',
        latency: 'CL16',
        voltage: '1.35V',
      },
    },
    {
      name: 'Corsair Vengeance LPX 16GB DDR4-3200',
      brand: 'Corsair',
      sku: 'SEED-RAM-COR-LPX-16G-3200',
      price: 950_000,
      category: catIds.ram,
      totalStock: 50,
      description: 'Kit DDR4 16GB (2×8GB) 3200 MHz CL16. Profile thấp, phổ biến và ổn định.',
      images: [img('https://bizweb.dktcdn.net/thumb/1024x1024/100/410/941/products/1-ff180d07-381c-4044-bace-29fb89c766ad.jpg?v=1635146851513')],
      specifications: {
        ramType: 'DDR4',
        tdp: 3,
        capacity: '16GB (2×8GB)',
        speed: '3200 MHz',
        latency: 'CL16',
        voltage: '1.35V',
      },
    },
    {
      name: 'Team T-Force Delta RGB 32GB DDR4-3600',
      brand: 'Team Group',
      sku: 'SEED-RAM-TG-DELTA-32G-3600',
      price: 2_100_000,
      category: catIds.ram,
      totalStock: 30,
      description: 'Kit DDR4 32GB (2×16GB) 3600 MHz CL18. RGB toàn viền, hiệu năng tốt.',
      images: [img('https://nguyencongpc.vn/media/product/18931-t-force-delta-1.jpg')],
      specifications: {
        ramType: 'DDR4',
        tdp: 4,
        capacity: '32GB (2×16GB)',
        speed: '3600 MHz',
        latency: 'CL18',
        voltage: '1.35V',
      },
    },

    // ══════════════════════════════════════════════════════════════════════════
    // SSD — 10 sản phẩm
    // ══════════════════════════════════════════════════════════════════════════
    {
      name: 'Samsung 990 Pro 2TB NVMe PCIe 4.0',
      brand: 'Samsung',
      sku: 'SEED-SSD-SAM-990PRO-2T',
      price: 3_200_000,
      category: catIds.ssd,
      totalStock: 25,
      description: 'SSD NVMe M.2 2TB. Đọc 7450 MB/s, Ghi 6900 MB/s. Ổ tốt nhất tầm trung.',
      images: [img('https://cdn.mos.cms.futurecdn.net/W2CKdCgQAAFeMDqEneEXqB.jpg')],
      specifications: {
        tdp: 8,
        capacity: '2TB',
        interface: 'PCIe 4.0 x4 (NVMe)',
        readSpeed: '7450 MB/s',
        writeSpeed: '6900 MB/s',
        formFactor: 'M.2 2280',
        warranty: '5 năm',
      },
    },
    {
      name: 'WD Black SN850X 1TB NVMe PCIe 4.0',
      brand: 'Western Digital',
      sku: 'SEED-SSD-WD-SN850X-1T',
      price: 2_100_000,
      category: catIds.ssd,
      totalStock: 30,
      description: 'SSD NVMe M.2 1TB. Đọc 7300 MB/s. Được khuyến nghị cho PS5 và gaming PC.',
      images: [img('https://cdn.mos.cms.futurecdn.net/XznGAj929i82MWrAHPH4Eo-2000-80.jpg')],
      specifications: {
        tdp: 7,
        capacity: '1TB',
        interface: 'PCIe 4.0 x4 (NVMe)',
        readSpeed: '7300 MB/s',
        writeSpeed: '6300 MB/s',
        formFactor: 'M.2 2280',
        warranty: '5 năm',
      },
    },
    {
      name: 'Crucial T700 2TB NVMe PCIe 5.0',
      brand: 'Crucial',
      sku: 'SEED-SSD-CRU-T700-2T',
      price: 4_500_000,
      category: catIds.ssd,
      totalStock: 15,
      description: 'SSD NVMe M.2 2TB thế hệ PCIe 5.0. Đọc 12400 MB/s. Nhanh nhất thị trường.',
      images: [img('https://lagihitech.vn/wp-content/uploads/2023/08/SSD-Crucial-T700-2TB-M2-PCIe-Gen-5.0-CT2000T700SSD3-hinh-3.jpg')],
      specifications: {
        tdp: 10,
        capacity: '2TB',
        interface: 'PCIe 5.0 x4 (NVMe)',
        readSpeed: '12400 MB/s',
        writeSpeed: '11800 MB/s',
        formFactor: 'M.2 2280',
        warranty: '5 năm',
      },
    },
    {
      name: 'Seagate FireCuda 530 2TB NVMe PCIe 4.0',
      brand: 'Seagate',
      sku: 'SEED-SSD-SEA-FC530-2T',
      price: 3_500_000,
      category: catIds.ssd,
      totalStock: 20,
      description: 'SSD NVMe M.2 2TB PCIe 4.0. Đọc 7300 MB/s. Hiệu năng cao, bảo hành 5 năm.',
      images: [img('https://lagihitech.vn/wp-content/uploads/2022/02/SSD-Seagate-Firecuda-530-2TB-M.2-PCIe-Gen4x4-NVMe-ZP2000GM30013-hinh-5.jpg')],
      specifications: {
        tdp: 8,
        capacity: '2TB',
        interface: 'PCIe 4.0 x4 (NVMe)',
        readSpeed: '7300 MB/s',
        writeSpeed: '6900 MB/s',
        formFactor: 'M.2 2280',
        warranty: '5 năm',
      },
    },
    {
      name: 'Kingston KC3000 2TB NVMe PCIe 4.0',
      brand: 'Kingston',
      sku: 'SEED-SSD-KNG-KC3000-2T',
      price: 3_000_000,
      category: catIds.ssd,
      totalStock: 22,
      description: 'SSD NVMe M.2 2TB PCIe 4.0. Đọc 7000 MB/s. Giải pháp hiệu năng cao giá tốt.',
      images: [img('https://bizweb.dktcdn.net/100/410/941/products/screenshot-2023-06-03-150039-eab0ac46-cdd3-47c3-8f91-8c32a70c2c3e-3e87c636-a90b-4736-b72a-798369ff3748.png?v=1685779752100')],
      specifications: {
        tdp: 8,
        capacity: '2TB',
        interface: 'PCIe 4.0 x4 (NVMe)',
        readSpeed: '7000 MB/s',
        writeSpeed: '7000 MB/s',
        formFactor: 'M.2 2280',
        warranty: '5 năm',
      },
    },
    {
      name: 'WD Blue SN580 1TB NVMe PCIe 4.0',
      brand: 'Western Digital',
      sku: 'SEED-SSD-WD-SN580-1T',
      price: 1_500_000,
      category: catIds.ssd,
      totalStock: 40,
      description: 'SSD NVMe M.2 1TB PCIe 4.0. Đọc 4150 MB/s. Entry-level PCIe 4.0 giá rẻ.',
      images: [img('https://c1.neweggimages.com/productimage/nb640/20-250-254-03.jpg')],
      specifications: {
        tdp: 5,
        capacity: '1TB',
        interface: 'PCIe 4.0 x4 (NVMe)',
        readSpeed: '4150 MB/s',
        writeSpeed: '4150 MB/s',
        formFactor: 'M.2 2280',
        warranty: '5 năm',
      },
    },
    {
      name: 'Samsung 870 EVO 1TB SATA',
      brand: 'Samsung',
      sku: 'SEED-SSD-SAM-870EVO-1T',
      price: 1_800_000,
      category: catIds.ssd,
      totalStock: 35,
      description: 'SSD SATA 2.5" 1TB. Đọc 560 MB/s. Ổn định tin cậy, phù hợp cho hệ thống cũ.',
      images: [img('https://product.hstatic.net/200000420363/product/ss-1t-ss-870-evo-ct_61f649600cdf4e62a8b3f4c23129d46d_master.jpg')],
      specifications: {
        tdp: 3,
        capacity: '1TB',
        interface: 'SATA III 6Gbps',
        readSpeed: '560 MB/s',
        writeSpeed: '530 MB/s',
        formFactor: '2.5"',
        warranty: '5 năm',
      },
    },
    {
      name: 'Crucial MX500 2TB SATA',
      brand: 'Crucial',
      sku: 'SEED-SSD-CRU-MX500-2T',
      price: 2_200_000,
      category: catIds.ssd,
      totalStock: 30,
      description: 'SSD SATA 2.5" 2TB. Đọc 560 MB/s. Lưu trữ lớn giá tốt, bảo hành 5 năm.',
      images: [img('https://tmp.phongvu.vn/wp-content/uploads/2018/10/-c%E1%BB%A9ng-SSD-Crucial-MX500-2.5-2TB-SATA-6.0Gbs-CT2000MX500SSD1_1-e1539148010456.jpg')],
      specifications: {
        tdp: 3,
        capacity: '2TB',
        interface: 'SATA III 6Gbps',
        readSpeed: '560 MB/s',
        writeSpeed: '510 MB/s',
        formFactor: '2.5"',
        warranty: '5 năm',
      },
    },
    {
      name: 'Corsair MP600 Pro LPX 2TB NVMe PCIe 5.0',
      brand: 'Corsair',
      sku: 'SEED-SSD-COR-MP600LPX-2T',
      price: 4_800_000,
      category: catIds.ssd,
      totalStock: 12,
      description: 'SSD NVMe M.2 2TB PCIe 5.0. Đọc 10000 MB/s. Profile thấp cho laptop và ITX build.',
      images: [img('https://www.tncstore.vn/media/product/10282-o-cung-ssd-corsair-mp600-pro-lpx-2tb--4-.jpg')],
      specifications: {
        tdp: 9,
        capacity: '2TB',
        interface: 'PCIe 5.0 x4 (NVMe)',
        readSpeed: '10000 MB/s',
        writeSpeed: '9500 MB/s',
        formFactor: 'M.2 2280',
        warranty: '5 năm',
      },
    },
    {
      name: 'ADATA XPG Gammix S70 Blade 2TB NVMe PCIe 4.0',
      brand: 'ADATA',
      sku: 'SEED-SSD-ADA-S70-2T',
      price: 2_800_000,
      category: catIds.ssd,
      totalStock: 20,
      description: 'SSD NVMe M.2 2TB PCIe 4.0. Đọc 7400 MB/s. Không tản nhiệt kèm theo, linh hoạt lắp ráp.',
      images: [img('https://songphuong.vn/Content/uploads/2021/11/SSD-Adata-Gammix-S70-2TB-2-songphuong.vn_.jpg')],
      specifications: {
        tdp: 8,
        capacity: '2TB',
        interface: 'PCIe 4.0 x4 (NVMe)',
        readSpeed: '7400 MB/s',
        writeSpeed: '6800 MB/s',
        formFactor: 'M.2 2280',
        warranty: '5 năm',
      },
    },

    // ══════════════════════════════════════════════════════════════════════════
    // PSU — 10 sản phẩm
    // ══════════════════════════════════════════════════════════════════════════
    {
      name: 'Corsair HX1000i 1000W 80+ Platinum',
      brand: 'Corsair',
      sku: 'SEED-PSU-COR-HX1000I',
      price: 5_800_000,
      category: catIds.psu,
      totalStock: 15,
      description: '1000W 80+ Platinum, fully modular. Đủ sức nuôi RTX 4090 + i9-14900K.',
      images: [img('https://anphat.com.vn/media/product/49583_ngu___n_m__y_t__nh_corsair_hx1000i_2023__4_.jpg')],
      specifications: {
        wattage: 1000,
        efficiency: '80+ Platinum',
        modular: 'Full',
        formFactor: 'ATX',
        fanSize: '135mm',
        protections: 'OVP, UVP, OCP, OTP, SCP',
      },
    },
    {
      name: 'Seasonic Prime TX-850 850W 80+ Titanium',
      brand: 'Seasonic',
      sku: 'SEED-PSU-SEA-TX850',
      price: 5_200_000,
      category: catIds.psu,
      totalStock: 12,
      description: '850W 80+ Titanium, fully modular. Hiệu suất đỉnh, fanless ở tải nhẹ.',
      images: [img('https://m.media-amazon.com/images/I/81hAGhDNlHL._AC_UF1000,1000_QL80_.jpg')],
      specifications: {
        wattage: 850,
        efficiency: '80+ Titanium',
        modular: 'Full',
        formFactor: 'ATX',
        fanSize: '135mm',
        protections: 'OVP, UVP, OCP, OTP, SCP',
      },
    },
    {
      name: 'EVGA SuperNOVA 650 G6 650W 80+ Gold',
      brand: 'EVGA',
      sku: 'SEED-PSU-EVGA-650G6',
      price: 2_900_000,
      category: catIds.psu,
      totalStock: 25,
      description: '650W 80+ Gold, fully modular. Lựa chọn tầm trung đáng tin cậy.',
      images: [img('https://cdn.mos.cms.futurecdn.net/fkwePc4KPQvDKSGskg8xkm.jpg')],
      specifications: {
        wattage: 650,
        efficiency: '80+ Gold',
        modular: 'Full',
        formFactor: 'ATX',
        fanSize: '92mm',
        protections: 'OVP, UVP, OCP, OTP, SCP',
      },
    },
    {
      name: 'Corsair RM1000x 1000W 80+ Gold',
      brand: 'Corsair',
      sku: 'SEED-PSU-COR-RM1000X',
      price: 4_800_000,
      category: catIds.psu,
      totalStock: 12,
      description: '1000W 80+ Gold, fully modular. Semi-passive, cực im lặng.',
      images: [img('https://www.tncstore.vn/media/product/9919-nguon-corsair-rm1000x-shift-1000.jpg')],
      specifications: {
        wattage: 1000,
        efficiency: '80+ Gold',
        modular: 'Full',
        formFactor: 'ATX',
        fanSize: '135mm',
        protections: 'OVP, UVP, OCP, OTP, SCP',
      },
    },
    {
      name: 'be quiet! Straight Power 11 850W 80+ Platinum',
      brand: 'be quiet!',
      sku: 'SEED-PSU-BQ-SP11-850P',
      price: 4_500_000,
      category: catIds.psu,
      totalStock: 10,
      description: '850W 80+ Platinum, fully modular. Cực kỳ im lặng, chất lượng Đức cao cấp.',
      images: [img('https://i.ytimg.com/vi/LymWD3vsWe8/maxresdefault.jpg')],
      specifications: {
        wattage: 850,
        efficiency: '80+ Platinum',
        modular: 'Full',
        formFactor: 'ATX',
        fanSize: '135mm',
        protections: 'OVP, UVP, OCP, OTP, SCP',
      },
    },
    {
      name: 'Cooler Master MWE Gold 750W V2',
      brand: 'Cooler Master',
      sku: 'SEED-PSU-CM-MWE750-V2',
      price: 2_200_000,
      category: catIds.psu,
      totalStock: 28,
      description: '750W 80+ Gold, fully modular. Tầm trung đáng tin cậy, giá tốt.',
      images: [img('https://bizweb.dktcdn.net/thumb/1024x1024/100/410/941/products/750wmodular.jpg?v=1676947882120')],
      specifications: {
        wattage: 750,
        efficiency: '80+ Gold',
        modular: 'Full',
        formFactor: 'ATX',
        fanSize: '120mm',
        protections: 'OVP, UVP, OCP, OTP, SCP',
      },
    },
    {
      name: 'Thermaltake Toughpower GF3 850W 80+ Gold',
      brand: 'Thermaltake',
      sku: 'SEED-PSU-TT-GF3-850',
      price: 3_500_000,
      category: catIds.psu,
      totalStock: 15,
      description: '850W 80+ Gold, fully modular. Hỗ trợ PCIe 5.0 16-pin native, phù hợp RTX 40xx.',
      images: [img('https://m.media-amazon.com/images/I/71HdcQaSnOL.jpg')],
      specifications: {
        wattage: 850,
        efficiency: '80+ Gold',
        modular: 'Full',
        formFactor: 'ATX',
        fanSize: '140mm',
        protections: 'OVP, UVP, OCP, OTP, SCP',
      },
    },
    {
      name: 'Seasonic Focus GX-650 650W 80+ Gold',
      brand: 'Seasonic',
      sku: 'SEED-PSU-SEA-FGX650',
      price: 2_600_000,
      category: catIds.psu,
      totalStock: 20,
      description: '650W 80+ Gold, fully modular. Chất lượng Seasonic nổi tiếng, bảo hành 10 năm.',
      images: [img('https://images-na.ssl-images-amazon.com/images/I/81JR4qhqzLL.jpg')],
      specifications: {
        wattage: 650,
        efficiency: '80+ Gold',
        modular: 'Full',
        formFactor: 'ATX',
        fanSize: '120mm',
        protections: 'OVP, UVP, OCP, OTP, SCP',
      },
    },
    {
      name: 'Super Flower Leadex Titanium 850W',
      brand: 'Super Flower',
      sku: 'SEED-PSU-SF-LTX850',
      price: 5_500_000,
      category: catIds.psu,
      totalStock: 8,
      description: '850W 80+ Titanium, fully modular. Hiệu suất > 92%, fan lớn 135mm siêu êm.',
      images: [img('https://cdn.cybassets.com/media/W1siZiIsIjIzNDMzL3Byb2R1Y3RzLzM4ODE3MzY1LzE2Njk4NzQ1MjNfYWE5NDMxNDM2YjJhN2M2MTY4MDEuanBlZyJdLFsicCIsInRodW1iIiwiNjAweDYwMCJdXQ.jpeg?sha=9e9a344d1ff52cf3')],
      specifications: {
        wattage: 850,
        efficiency: '80+ Titanium',
        modular: 'Full',
        formFactor: 'ATX',
        fanSize: '135mm',
        protections: 'OVP, UVP, OCP, OTP, SCP',
      },
    },
    {
      name: 'MSI MAG A850GL PCIE5 850W 80+ Gold',
      brand: 'MSI',
      sku: 'SEED-PSU-MSI-A850GL',
      price: 3_200_000,
      category: catIds.psu,
      totalStock: 18,
      description: '850W 80+ Gold, fully modular. Cổng PCIe 5.0 16-pin native, ATX 3.0.',
      images: [img('https://phucanhcdn.com/media/lib/14-03-2025/chan-trang-thang-3-bai-22-1.jpg')],
      specifications: {
        wattage: 850,
        efficiency: '80+ Gold',
        modular: 'Full',
        formFactor: 'ATX',
        fanSize: '135mm',
        protections: 'OVP, UVP, OCP, OTP, SCP',
      },
    },

    // ══════════════════════════════════════════════════════════════════════════
    // CASE — 10 sản phẩm
    // ══════════════════════════════════════════════════════════════════════════
    {
      name: 'Lian Li PC-O11D EVO XL',
      brand: 'Lian Li',
      sku: 'SEED-CASE-O11D-EVO-XL',
      price: 5_500_000,
      category: catIds.case,
      totalStock: 10,
      description: 'Full Tower. Khoang VGA 420mm, tản nhiệt 167mm. Hỗ trợ ATX / E-ATX.',
      images: [img('https://product.hstatic.net/200000522285/product/_o11_dynamic_evo_xl_black__white_trang_-_o11d_evo_xl_-_chinh_hang__10__5826f4c5792c447f92ab8d11b35ab449.png')],
      specifications: {
        maxGPULength: 420,
        maxCPUCoolerHeight: 167,
        supportedForms: ['ATX', 'E-ATX', 'm-ATX'],
        formFactor: 'Full Tower',
        material: 'Nhôm + Kính cường lực',
        driveBays: '4× 3.5", 4× 2.5"',
      },
    },
    {
      name: 'Fractal Design Meshify 2 XL',
      brand: 'Fractal Design',
      sku: 'SEED-CASE-MESHIFY2-XL',
      price: 4_200_000,
      category: catIds.case,
      totalStock: 14,
      description: 'Full Tower tản nhiệt đỉnh. GPU 461mm, tản nhiệt 185mm. ATX / E-ATX.',
      images: [img('https://m.media-amazon.com/images/S/aplus-media/vc/31efdcfb-590d-4f95-ba87-fb9a99ba5021.__CR0,0,1501,928_PT0_SX970_V1___.png')],
      specifications: {
        maxGPULength: 461,
        maxCPUCoolerHeight: 185,
        supportedForms: ['ATX', 'E-ATX', 'm-ATX'],
        formFactor: 'Full Tower',
        material: 'Thép + Kính cường lực',
        driveBays: '2× 3.5", 6× 2.5"',
      },
    },
    {
      name: 'NZXT H7 Flow 2024',
      brand: 'NZXT',
      sku: 'SEED-CASE-H7-FLOW',
      price: 3_100_000,
      category: catIds.case,
      totalStock: 20,
      description: 'Mid Tower tản nhiệt tốt. GPU 380mm, tản nhiệt 185mm. ATX / m-ATX.',
      images: [img('https://static.tandoanh.vn/wp-content/uploads/2024/11/NZXT-H7-Flow-RGB-2024-Black-H1.jpg')],
      specifications: {
        maxGPULength: 380,
        maxCPUCoolerHeight: 185,
        supportedForms: ['ATX', 'm-ATX'],
        formFactor: 'Mid Tower',
        material: 'Thép + Kính cường lực',
        driveBays: '2× 3.5", 3× 2.5"',
      },
    },
    {
      name: 'Corsair 5000D Airflow',
      brand: 'Corsair',
      sku: 'SEED-CASE-5000D-AIRFLOW',
      price: 3_800_000,
      category: catIds.case,
      totalStock: 16,
      description: 'Mid Tower luồng khí tuyệt vời. GPU 420mm, tản nhiệt 170mm. Lưới thép mật độ cao.',
      images: [img('https://product.hstatic.net/1000037809/product/thegioigear__icue_5000d_rgb_airflow_3_c159d4b37619475095ecf73adb00323a_master.jpg')],
      specifications: {
        maxGPULength: 420,
        maxCPUCoolerHeight: 170,
        supportedForms: ['ATX', 'E-ATX', 'm-ATX'],
        formFactor: 'Mid Tower',
        material: 'Thép + Kính cường lực',
        driveBays: '2× 3.5", 6× 2.5"',
      },
    },
    {
      name: 'be quiet! Pure Base 500DX',
      brand: 'be quiet!',
      sku: 'SEED-CASE-BQ-PB500DX',
      price: 2_500_000,
      category: catIds.case,
      totalStock: 18,
      description: 'Mid Tower tiêu âm + ARGB. GPU 369mm, tản nhiệt 190mm. Im lặng vượt trội.',
      images: [img('https://pcper.com/wp-content/uploads/2020/04/be-quiet-pure-base-500dx-0342.jpg')],
      specifications: {
        maxGPULength: 369,
        maxCPUCoolerHeight: 190,
        supportedForms: ['ATX', 'm-ATX'],
        formFactor: 'Mid Tower',
        material: 'Thép + Kính cường lực',
        driveBays: '3× 3.5", 3× 2.5"',
      },
    },
    {
      name: 'Phanteks Enthoo Pro 2',
      brand: 'Phanteks',
      sku: 'SEED-CASE-PHANTEKS-EP2',
      price: 4_500_000,
      category: catIds.case,
      totalStock: 8,
      description: 'Full Tower rộng lớn. GPU 503mm, tản nhiệt 200mm. Hỗ trợ E-ATX và dual-system.',
      images: [img('https://phanteks.com/wp-content/uploads/2024/04/cards_Enthoo_Pro-II-SE.webp')],
      specifications: {
        maxGPULength: 503,
        maxCPUCoolerHeight: 200,
        supportedForms: ['ATX', 'E-ATX', 'm-ATX'],
        formFactor: 'Full Tower',
        material: 'Thép + Kính cường lực',
        driveBays: '4× 3.5", 6× 2.5"',
      },
    },
    {
      name: 'NZXT H9 Flow',
      brand: 'NZXT',
      sku: 'SEED-CASE-H9-FLOW',
      price: 4_000_000,
      category: catIds.case,
      totalStock: 12,
      description: 'Mid Tower cao cấp dual-chamber. GPU 435mm, tản nhiệt 185mm. Kính 4 mặt.',
      images: [img('https://www.tncstore.vn/media/product/8014-vo-case-nzxt-h9-flow-black-1.jpg')],
      specifications: {
        maxGPULength: 435,
        maxCPUCoolerHeight: 185,
        supportedForms: ['ATX', 'm-ATX'],
        formFactor: 'Mid Tower',
        material: 'Thép + Kính cường lực',
        driveBays: '2× 3.5", 4× 2.5"',
      },
    },
    {
      name: 'Cooler Master HAF 700 EVO',
      brand: 'Cooler Master',
      sku: 'SEED-CASE-CM-HAF700-EVO',
      price: 6_800_000,
      category: catIds.case,
      totalStock: 6,
      description: 'Full Tower Extreme. GPU 490mm, tản nhiệt 210mm. Màn hình LCD mặt trước.',
      images: [img('https://hanoicomputercdn.com/media/product/66369_haf_700evo__2_.jpg')],
      specifications: {
        maxGPULength: 490,
        maxCPUCoolerHeight: 210,
        supportedForms: ['ATX', 'E-ATX', 'm-ATX'],
        formFactor: 'Full Tower',
        material: 'Nhôm + Kính cường lực',
        driveBays: '3× 3.5", 4× 2.5"',
      },
    },
    {
      name: 'Antec P120 Crystal',
      brand: 'Antec',
      sku: 'SEED-CASE-ANTEC-P120',
      price: 2_800_000,
      category: catIds.case,
      totalStock: 15,
      description: 'Mid Tower kính cường lực 4 mặt. GPU 400mm, tản nhiệt 185mm. Giá tốt.',
      images: [img('https://i.ytimg.com/vi/XhsR8_iLypg/maxresdefault.jpg')],
      specifications: {
        maxGPULength: 400,
        maxCPUCoolerHeight: 185,
        supportedForms: ['ATX', 'm-ATX'],
        formFactor: 'Mid Tower',
        material: 'Thép + Kính cường lực',
        driveBays: '2× 3.5", 4× 2.5"',
      },
    },
    {
      name: 'Thermaltake Core P6 TG Snow',
      brand: 'Thermaltake',
      sku: 'SEED-CASE-TT-COREP6-SNOW',
      price: 5_000_000,
      category: catIds.case,
      totalStock: 7,
      description: 'Mid Tower open-frame. GPU 420mm, tản nhiệt 185mm. Trưng bày linh kiện đẹp mắt.',
      images: [img('https://product.hstatic.net/200000722513/product/corep6tg_w01_fbf7ea62388d4cdbbc459413122f1480_d2cc002c44be41b8a07e12adcd6417d5_master.jpg')],
      specifications: {
        maxGPULength: 420,
        maxCPUCoolerHeight: 185,
        supportedForms: ['ATX', 'E-ATX', 'm-ATX'],
        formFactor: 'Mid Tower',
        material: 'Thép + Kính cường lực',
        driveBays: '2× 3.5", 4× 2.5"',
      },
    },

    // ══════════════════════════════════════════════════════════════════════════
    // COOLER — 10 sản phẩm
    // ══════════════════════════════════════════════════════════════════════════
    {
      name: 'Noctua NH-D15 chromax.black',
      brand: 'Noctua',
      sku: 'SEED-COOL-NOCTUA-NHD15',
      price: 2_800_000,
      category: catIds.cooler,
      totalStock: 18,
      description: 'Tản nhiệt khí đôi tháp. Cao 165mm, TDP support 250W. LGA1700 + AM5.',
      images: [img('https://cdn.hstatic.net/products/200000837185/nh_d15_chromax_black_5_1_f967904efc0441c6a16b1b49d4c0d890_9ba733fb5e684c0bba2ae6fcc2cf289b_master.jpg')],
      specifications: {
        height: 165,
        tdpSupport: 250,
        sockets: ['LGA1700', 'LGA1200', 'AM5', 'AM4'],
        type: 'Air (Dual Tower)',
        fanCount: '2× 140mm',
        noise: '24.6 dB(A)',
      },
    },
    {
      name: 'be quiet! Dark Rock Pro 4',
      brand: 'be quiet!',
      sku: 'SEED-COOL-BQ-DRP4',
      price: 2_200_000,
      category: catIds.cooler,
      totalStock: 15,
      description: 'Tản nhiệt khí siêu im lặng. Cao 162mm, TDP support 250W. Dual Tower.',
      images: [img('https://www.ukgamingcomputers.co.uk/wp/wp-content/uploads/2018/09/IMG_3511-1024x683.jpg')],
      specifications: {
        height: 162,
        tdpSupport: 250,
        sockets: ['LGA1700', 'LGA1200', 'AM5', 'AM4'],
        type: 'Air (Dual Tower)',
        fanCount: '2× 135mm',
        noise: '24.3 dB(A)',
      },
    },
    {
      name: 'Cooler Master Hyper 212 Halo Black',
      brand: 'Cooler Master',
      sku: 'SEED-COOL-CM-H212-HALO',
      price: 680_000,
      category: catIds.cooler,
      totalStock: 40,
      description: 'Tản nhiệt giá rẻ phổ biến. Cao 158mm, TDP support 150W. Mọi build tầm trung.',
      images: [img('https://storage.tweak.dk/k%C3%B8ling/Cooler%20Master%20Hyper%20212%20HALO%20Black/Pipes%20212%20HALO%20Heat%20Black%20Intel%20Aluminum%20air%20ARGB%20AMD%20Sleek%20cooler%20BLACK%20HYPER%20CPU%20MF120.JPG')],
      specifications: {
        height: 158,
        tdpSupport: 150,
        sockets: ['LGA1700', 'LGA1200', 'AM5', 'AM4'],
        type: 'Air (Single Tower)',
        fanCount: '1× 120mm ARGB',
        noise: '27 dB(A)',
      },
    },
    {
      name: 'NZXT Kraken X73 360mm AIO',
      brand: 'NZXT',
      sku: 'SEED-COOL-NZXT-X73-360',
      price: 4_500_000,
      category: catIds.cooler,
      totalStock: 12,
      description: 'AIO 360mm LCD display. Cao 52mm (pump). TDP support 300W. LGA1700 + AM5.',
      images: [img('https://product.hstatic.net/1000333506/product/51280_kraken_x73_4_5246e464373d41d69132f78957158885.png')],
      specifications: {
        height: 52,
        tdpSupport: 300,
        sockets: ['LGA1700', 'LGA1200', 'AM5', 'AM4'],
        type: 'Liquid AIO 360mm',
        fanCount: '3× 120mm',
        noise: '21-36 dB(A)',
      },
    },
    {
      name: 'Corsair iCUE H150i Elite LCD 360mm AIO',
      brand: 'Corsair',
      sku: 'SEED-COOL-COR-H150I-LCD',
      price: 5_200_000,
      category: catIds.cooler,
      totalStock: 10,
      description: 'AIO 360mm màn hình LCD 2.1". Cao 54mm (pump). TDP support 350W.',
      images: [img('https://ecommerce.datablitz.com.ph/cdn/shop/products/base-elite-lcd-xt-cooler-config-Gallery-H150i-ELITE-LCD-XT-05_800x.jpg?v=1677830102')],
      specifications: {
        height: 54,
        tdpSupport: 350,
        sockets: ['LGA1700', 'LGA1200', 'AM5', 'AM4'],
        type: 'Liquid AIO 360mm',
        fanCount: '3× 120mm',
        noise: '10-36 dB(A)',
      },
    },
    {
      name: 'Arctic Liquid Freezer II 280mm AIO',
      brand: 'Arctic',
      sku: 'SEED-COOL-ARC-LF2-280',
      price: 2_100_000,
      category: catIds.cooler,
      totalStock: 20,
      description: 'AIO 280mm giá tốt nhất phân khúc. Cao 53mm (pump). TDP support 300W.',
      images: [img('https://assetsio.gnwcdn.com/280_nkOv9nK.jpg?width=690&quality=85&format=jpg&dpr=3&auto=webp')],
      specifications: {
        height: 53,
        tdpSupport: 300,
        sockets: ['LGA1700', 'LGA1200', 'AM5', 'AM4'],
        type: 'Liquid AIO 280mm',
        fanCount: '2× 140mm',
        noise: '12.5-22.5 dB(A)',
      },
    },
    {
      name: 'Lian Li Galahad II LCD 360mm AIO',
      brand: 'Lian Li',
      sku: 'SEED-COOL-LL-GALAHAD2-360',
      price: 4_800_000,
      category: catIds.cooler,
      totalStock: 10,
      description: 'AIO 360mm với đầu pump LCD đẹp. Cao 56mm. TDP support 350W. ARGB sync.',
      images: [img('https://ecommerce.datablitz.com.ph/cdn/shop/files/nfgg_800x.jpg?v=1699166649')],
      specifications: {
        height: 56,
        tdpSupport: 350,
        sockets: ['LGA1700', 'LGA1200', 'AM5', 'AM4'],
        type: 'Liquid AIO 360mm',
        fanCount: '3× 120mm ARGB',
        noise: '16-28.5 dB(A)',
      },
    },
    {
      name: 'Thermalright Peerless Assassin 120 SE',
      brand: 'Thermalright',
      sku: 'SEED-COOL-TR-PA120SE',
      price: 750_000,
      category: catIds.cooler,
      totalStock: 35,
      description: 'Tản nhiệt khí dual tower siêu rẻ. Cao 155mm, TDP support 220W. Hiệu năng/giá tốt nhất.',
      images: [img('https://minhancomputercdn.com/media/product/11106_peerless_assassin_120_se_white_argb_1.jpg')],
      specifications: {
        height: 155,
        tdpSupport: 220,
        sockets: ['LGA1700', 'LGA1200', 'AM5', 'AM4'],
        type: 'Air (Dual Tower)',
        fanCount: '2× 120mm',
        noise: '25.6 dB(A)',
      },
    },
    {
      name: 'DeepCool AK620 Zero Dark',
      brand: 'DeepCool',
      sku: 'SEED-COOL-DP-AK620-ZERO',
      price: 1_200_000,
      category: catIds.cooler,
      totalStock: 25,
      description: 'Tản nhiệt khí dual tower all-black. Cao 160mm, TDP support 260W. Hoàn toàn đen mờ.',
      images: [img('https://bizweb.dktcdn.net/thumb/1024x1024/100/329/122/products/tan-nhiet-khi-deepcool-ak620-zero-dark-r-ak620-bknnmt-g-1.jpg?v=1748921679607')],
      specifications: {
        height: 160,
        tdpSupport: 260,
        sockets: ['LGA1700', 'LGA1200', 'AM5', 'AM4'],
        type: 'Air (Dual Tower)',
        fanCount: '2× 120mm',
        noise: '28 dB(A)',
      },
    },
    {
      name: 'ID-Cooling SE-914-XT Black',
      brand: 'ID-Cooling',
      sku: 'SEED-COOL-IDC-SE914XT-BLK',
      price: 550_000,
      category: catIds.cooler,
      totalStock: 45,
      description: 'Tản nhiệt khí single tower entry. Cao 154mm, TDP support 180W. Giải pháp giá rẻ nhất.',
      images: [img('https://tpucdn.com/review/id-cooling-se-914-xt-argb-se-914-xt-basic-92-mm-cpu-coolers/images/title.jpg')],
      specifications: {
        height: 154,
        tdpSupport: 180,
        sockets: ['LGA1700', 'LGA1200', 'AM5', 'AM4'],
        type: 'Air (Single Tower)',
        fanCount: '1× 92mm',
        noise: '25.2 dB(A)',
      },
    },

    // ══════════════════════════════════════════════════════════════════════════
    // LAPTOP GAMING — 6 sản phẩm (ảnh: placeholder — thay URL trong img('...') khi có)
    // ══════════════════════════════════════════════════════════════════════════
    {
      name: 'ASUS ROG Strix G16 (2024)',
      brand: 'ASUS',
      sku: 'SEED-LG-STX-G16-2024',
      price: 38_990_000,
      category: catIds['laptop-gaming'],
      totalStock: 8,
      description: 'Gaming laptop 16 inch QHD+ 165Hz — Intel Core i9-14900HX, RTX 4070.',
      images: [img('https://ttcenter.com.vn/uploads/product/mjbshlw6-1348-asus-rog-zephyrus-g16-2024-gu605mi-qr116w-intel-core-ultra-9-185h-16gb-1tb-geforce-rtx-4070-8gb-16-2-5k-oled-240hz-new.jpg')],
      specifications: {
        processor: 'Intel Core i9-14900HX',
        gpu: 'NVIDIA GeForce RTX 4070 8GB',
        ram: '32GB DDR5',
        storage: '1TB NVMe SSD',
      },
    },
    {
      name: 'Lenovo Legion Pro 7i Gen 9',
      brand: 'Lenovo',
      sku: 'SEED-LG-LNV-LP7-G9',
      price: 55_990_000,
      category: catIds['laptop-gaming'],
      totalStock: 5,
      description: '16 inch WQXGA Mini-LED — Core i9-14900HX, RTX 4080.',
      images: [img('https://sm.pcmag.com/t/pcmag_me/review/l/lenovo-leg/lenovo-legion-pro-7i-gen-9-16_b7a8.1200.jpg')],
      specifications: {
        processor: 'Intel Core i9-14900HX',
        gpu: 'NVIDIA GeForce RTX 4080 12GB',
        ram: '32GB DDR5',
        storage: '2TB NVMe SSD',
      },
    },
    {
      name: 'MSI Titan 18 HX (2024)',
      brand: 'MSI',
      sku: 'SEED-LG-MSI-TITAN18-HX',
      price: 119_990_000,
      category: catIds['laptop-gaming'],
      totalStock: 2,
      description: '18 inch UHD+ — Core Ultra 9 / RTX 4090 workstation gaming.',
      images: [img('https://sm.pcmag.com/pcmag_me/review/m/msi-titan-/msi-titan-18-hx_wzy6.jpg')],
      specifications: {
        processor: 'Intel Core Ultra 9 185HX',
        gpu: 'NVIDIA GeForce RTX 4090 16GB',
        ram: '64GB DDR5',
        storage: '2TB NVMe RAID',
      },
    },
    {
      name: 'Acer Nitro V 16 ANV16-41',
      brand: 'Acer',
      sku: 'SEED-LG-ACER-NITRO-V16',
      price: 24_490_000,
      category: catIds['laptop-gaming'],
      totalStock: 14,
      description: '16 inch FHD 165Hz — Ryzen 7 8845HS, RTX 4060.',
      images: [img('https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/44/332579/acer-nitro-v-16-propanel-anv16-41-r6zy-r5-nhqp2sv002-1-638684879675326418-750x500.jpg')],
      specifications: {
        processor: 'AMD Ryzen 7 8845HS',
        gpu: 'NVIDIA GeForce RTX 4060 8GB',
        ram: '16GB DDR5',
        storage: '512GB NVMe SSD',
      },
    },
    {
      name: 'ASUS TUF Gaming A15 FA507NV',
      brand: 'ASUS',
      sku: 'SEED-LG-TUF-A15-FA507NV',
      price: 22_990_000,
      category: catIds['laptop-gaming'],
      totalStock: 16,
      description: '15.6 inch FHD 165Hz — Ryzen 7 7435HS, RTX 4050.',
      images: [img('https://nguyencongpc.vn/media/lib/05-05-2023/laptopasustufgaminga15fa507nv-lp046w2.jpeg')],
      specifications: {
        processor: 'AMD Ryzen 7 7435HS',
        gpu: 'NVIDIA GeForce RTX 4050 6GB',
        ram: '16GB DDR5',
        storage: '512GB NVMe SSD',
      },
    },
    {
      name: 'HP OMEN Transcend 16-u1xxx',
      brand: 'HP',
      sku: 'SEED-LG-HP-OMEN-TR16',
      price: 44_990_000,
      category: catIds['laptop-gaming'],
      totalStock: 7,
      description: '16 inch QHD 240Hz — Core i9-14900HX, RTX 4070.',
      images: [img('https://sm.pcmag.com/t/pcmag_au/review/h/hp-omen-tr/hp-omen-transcend-16-2024_akke.1200.jpg')],
      specifications: {
        processor: 'Intel Core i9-14900HX',
        gpu: 'NVIDIA GeForce RTX 4070 8GB',
        ram: '32GB DDR5',
        storage: '1TB NVMe SSD',
      },
    },

    // ══════════════════════════════════════════════════════════════════════════
    // LAPTOP VĂN PHÒNG — 6
    // ══════════════════════════════════════════════════════════════════════════
    {
      name: 'Dell Inspiron 16 5635',
      brand: 'Dell',
      sku: 'SEED-LVP-DELL-5635',
      price: 16_990_000,
      category: catIds['laptop-van-phong'],
      totalStock: 20,
      description: '16 inch FHD+ — Ryzen 7 7735U, tích pin dài.',
      images: [img('https://www.laptopvip.vn/images/companies/1/JVS/DELL/Dell-Inspiron/2023/ins-5635/laptop-inspiron-16-5635-amd-pdp-mod04a.jpg?1687778874178')],
      specifications: {
        processor: 'AMD Ryzen 7 7735U',
        gpu: 'AMD Radeon Graphics',
        ram: '16GB DDR5',
        storage: '512GB NVMe SSD',
      },
    },
    {
      name: 'Lenovo IdeaPad Slim 5 14IMH9',
      brand: 'Lenovo',
      sku: 'SEED-LVP-IDEAPAD-S5-14IMH9',
      price: 14_490_000,
      category: catIds['laptop-van-phong'],
      totalStock: 22,
      description: '14 inch WUXGA OLED — Ultra 5 125H.',
      images: [img('https://www.civip.com.vn/media/product/9912_25780_lenovo_ideapad_slim_3_14irh8_83el0023vn_1.jpg')],
      specifications: {
        processor: 'Intel Core Ultra 5 125H',
        gpu: 'Intel Arc Graphics',
        ram: '16GB LPDDR5X',
        storage: '512GB NVMe SSD',
      },
    },
    {
      name: 'ASUS ExpertBook B5 OLED B5602',
      brand: 'ASUS',
      sku: 'SEED-LVP-EXP-B5602',
      price: 19_990_000,
      category: catIds['laptop-van-phong'],
      totalStock: 12,
      description: 'Business 16 inch OLED — Core Ultra 7, siêu nhẹ.',
      images: [img('https://laptopmedia.com/wp-content/uploads/2023/06/asusexpertbookb5oledb5602featured.jpg')],
      specifications: {
        processor: 'Intel Core Ultra 7 155U',
        gpu: 'Intel Graphics',
        ram: '16GB DDR5',
        storage: '1TB NVMe SSD',
      },
    },
    {
      name: 'HP Pavilion 14-eg2xxx',
      brand: 'HP',
      sku: 'SEED-LVP-HP-PAV14-EG2',
      price: 13_490_000,
      category: catIds['laptop-van-phong'],
      totalStock: 25,
      description: '14 inch FHD — Core i5-1335U, văn phòng học sinh.',
      images: [img('https://cdn.ankhang.vn/media/product/22508_laptop_hp_pavilion_15_eg2081tu_vang_gold.jpg')],
      specifications: {
        processor: 'Intel Core i5-1335U',
        gpu: 'Intel Iris Xe Graphics',
        ram: '8GB DDR4',
        storage: '512GB NVMe SSD',
      },
    },
    {
      name: 'Acer Swift Go 14 SFG14-71',
      brand: 'Acer',
      sku: 'SEED-LVP-SW-GO14-SFG',
      price: 15_990_000,
      category: catIds['laptop-van-phong'],
      totalStock: 18,
      description: '14 inch 2.8K OLED — Core Ultra 5 125H.',
      images: [img('https://cdnv2.tgdd.vn/mwg-static/common/News/1571713/Acer-Swif-Go-SFG14-71-513F-5.jpg')],
      specifications: {
        processor: 'Intel Core Ultra 5 125H',
        gpu: 'Intel Arc Graphics',
        ram: '16GB LPDDR5X',
        storage: '512GB NVMe SSD',
      },
    },
    {
      name: 'MSI Modern 15 H AI C1',
      brand: 'MSI',
      sku: 'SEED-LVP-MODERN15-H',
      price: 12_490_000,
      category: catIds['laptop-van-phong'],
      totalStock: 20,
      description: '15.6 inch FHD — Meteor Lake nhẹ chỉ ~1.5kg.',
      images: [img('https://product.hstatic.net/1000233206/product/15h_ai_c2hmg-220vn_4_50f12d1a18464d9ab1751214f402eea2_1024x1024.png')],
      specifications: {
        processor: 'Intel Core Ultra 7 155H',
        gpu: 'Intel Arc Graphics',
        ram: '16GB DDR5',
        storage: '512GB NVMe SSD',
      },
    },

    // ══════════════════════════════════════════════════════════════════════════
    // LAPTOP ĐỒ HỌA — 6
    // ══════════════════════════════════════════════════════════════════════════
    {
      name: 'MSI Creator Z16 HX Studio',
      brand: 'MSI',
      sku: 'SEED-LDH-Z16HX-STUDIO',
      price: 62_990_000,
      category: catIds['laptop-do-hoa'],
      totalStock: 4,
      description: '16 inch QHD+ Mini-LED — RTX Studio, render & Adobe.',
      images: [img('https://minhancomputercdn.com/media/product/13511_msi_creator_z16_hx_studio_b13vfto_063vn_01_result.jpg')],
      specifications: {
        processor: 'Intel Core i9-14900HX',
        gpu: 'NVIDIA RTX Studio 4070 8GB',
        ram: '64GB DDR5',
        storage: '2TB NVMe SSD',
      },
    },
    {
      name: 'ASUS ProArt StudioBook 16 OLED H7604',
      brand: 'ASUS',
      sku: 'SEED-LDH-PA-STUDIO16-OLED',
      price: 58_990_000,
      category: catIds['laptop-do-hoa'],
      totalStock: 5,
      description: '16 inch OLED 3.2K 120Hz — RTX Ada cho đồ họa & video.',
      images: [img('https://onlylap.vn/wp-content/uploads/2024/04/Asus-ProArt-Studiobook-16-OLED-H7600ZM-L2079W-1.webp')],
      specifications: {
        processor: 'Intel Core i9-13980HX',
        gpu: 'NVIDIA GeForce RTX 4070 8GB',
        ram: '32GB DDR5',
        storage: '1TB NVMe SSD',
      },
    },
    {
      name: 'Dell Precision 5690 Mobile Workstation',
      brand: 'Dell',
      sku: 'SEED-LDH-DELL-P5690',
      price: 89_990_000,
      category: catIds['laptop-do-hoa'],
      totalStock: 3,
      description: '16 inch UHD+ — Nvidia RTX Ada / ISV certified.',
      images: [img('https://mac24h.vn/images/detailed/94/workstation-precision-16-5690-black-gallery-2-mac24h.png.webp')],
      specifications: {
        processor: 'Intel Ultra 9 (workstation tier)',
        gpu: 'NVIDIA RTX 3500 Ada 12GB',
        ram: '32GB DDR5',
        storage: '1TB NVMe SSD',
      },
    },
    {
      name: 'Lenovo ThinkPad P1 Gen 7',
      brand: 'Lenovo',
      sku: 'SEED-LDH-TP-P1-G7',
      price: 72_990_000,
      category: catIds['laptop-do-hoa'],
      totalStock: 4,
      description: 'Mobile workstation 16 inch — RTX/A-series cho AI & CAD.',
      images: [img('https://static.hungphatlaptop.com/wp-content/uploads/2024/07/Lenovo-ThinkPad-P1-Gen-7-Mobile-WorkStation-2024-Features-07.jpeg')],
      specifications: {
        processor: 'Intel Core Ultra 9 185H',
        gpu: 'NVIDIA RTX 2000 Ada 8GB',
        ram: '32GB DDR5',
        storage: '1TB NVMe SSD',
      },
    },
    {
      name: 'ASUS Zenbook Pro 16 OLED UX7602',
      brand: 'ASUS',
      sku: 'SEED-LDH-ZB-PRO16-OLED',
      price: 42_990_000,
      category: catIds['laptop-do-hoa'],
      totalStock: 8,
      description: '16 inch 3.2K OLED — Core i9 + RTX tối ưu đồ họa sáng tạo.',
      images: [img('https://cdn.ankhang.vn/media/product/22198_ux7602zm_me107w.jpg')],
      specifications: {
        processor: 'Intel Core i9-13900H',
        gpu: 'NVIDIA GeForce RTX 4070 8GB',
        ram: '32GB DDR5',
        storage: '1TB NVMe SSD',
      },
    },
    {
      name: 'HP ZBook Firefly 14 inch G11',
      brand: 'HP',
      sku: 'SEED-LDH-ZBOOK-FF-G11',
      price: 48_990_000,
      category: catIds['laptop-do-hoa'],
      totalStock: 6,
      description: 'Workstation nhẹ ~1.45kg — ISV Nvidia RTX Ada.',
      images: [img('https://i.pcmag.com/imagery/reviews/06cmxJSSGMxipwSsU1j0Dus-2.fit_lim.size_1050x.jpg')],
      specifications: {
        processor: 'Intel Core Ultra 7',
        gpu: 'NVIDIA RTX 1000 Ada 6GB',
        ram: '32GB DDR5',
        storage: '1TB NVMe SSD',
      },
    },

    // ══════════════════════════════════════════════════════════════════════════
    // MÁY TÍNH BỘ — 6
    // ══════════════════════════════════════════════════════════════════════════
    {
      name: 'ASUS ROG G700 (2025) Prebuilt',
      brand: 'ASUS',
      sku: 'SEED-MTB-RG-G700',
      price: 65_990_000,
      category: catIds['may-tinh-bo'],
      totalStock: 6,
      description: 'PC gaming build sẵn RTX 4080 SUPER, i7-14700KF, AIO RGB.',
      images: [img('https://i.ytimg.com/vi/3kRkHUa46zc/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDwMgR7WuP9VSFwwSILzyLlaCSZ-g')],
      specifications: {
        cpuModel: 'Intel Core i7-14700KF',
        gpuModel: 'NVIDIA GeForce RTX 4080 SUPER 16GB',
        ram: '32GB DDR5',
        storage: '1TB NVMe SSD',
      },
    },
    {
      name: 'MSI MAG Infinite S3 13NUC',
      brand: 'MSI',
      sku: 'SEED-MTB-INF-S3',
      price: 24_490_000,
      category: catIds['may-tinh-bo'],
      totalStock: 12,
      description: 'PC compact RTX 4060, Intel Core i7-14700.',
      images: [img('https://i.ebayimg.com/images/g/uEoAAOSwc2VnIgO0/s-l1200.jpg')],
      specifications: {
        cpuModel: 'Intel Core i7-14700',
        gpuModel: 'NVIDIA GeForce RTX 4060 8GB',
        ram: '16GB DDR5',
        storage: '1TB NVMe SSD',
      },
    },
    {
      name: 'Dell XPS Desktop 8960',
      brand: 'Dell',
      sku: 'SEED-MTB-DELL-XPS8960',
      price: 38_490_000,
      category: catIds['may-tinh-bo'],
      totalStock: 9,
      description: 'Đồng bộ workstation — RTX chạy Blender & Office.',
      images: [img('https://i.pcmag.com/imagery/reviews/06lcPhXPNOavejs9BYVcNqB-1..v1731687944.jpg')],
      specifications: {
        cpuModel: 'Intel Core i7-13700',
        gpuModel: 'NVIDIA GeForce RTX 4060 Ti 16GB',
        ram: '32GB DDR5',
        storage: '1TB NVMe SSD',
      },
    },
    {
      name: 'HP OMEN 25L Gaming Desktop GT15-2000xxx',
      brand: 'HP',
      sku: 'SEED-MTB-HP-OMEN25L',
      price: 29_990_000,
      category: catIds['may-tinh-bo'],
      totalStock: 11,
      description: 'Tower gaming RTX 4060, Ryzen 7 8700G.',
      images: [img('https://cdn.tgdd.vn/Files/2020/05/05/1253577/omen-hp-2_800x512.jpg')],
      specifications: {
        cpuModel: 'AMD Ryzen 7 8700G',
        gpuModel: 'NVIDIA GeForce RTX 4060 8GB',
        ram: '16GB DDR5',
        storage: '1TB SSD',
      },
    },
    {
      name: 'Acer Predator Orion 3000 PO3-655',
      brand: 'Acer',
      sku: 'SEED-MTB-ACER-OR3000',
      price: 35_990_000,
      category: catIds['may-tinh-bo'],
      totalStock: 8,
      description: 'Predator RTX 4070, Core i7-14700F — vỏ mesh tản tốt.',
      images: [img('https://cohotech.vn/wp-content/uploads/2025/04/Acer-Predator-Orion-3000-8.jpg')],
      specifications: {
        cpuModel: 'Intel Core i7-14700F',
        gpuModel: 'NVIDIA GeForce RTX 4070 12GB',
        ram: '32GB DDR5',
        storage: '1TB SSD',
      },
    },
    {
      name: 'Lenovo Legion Tower 5 Gen 10',
      brand: 'Lenovo',
      sku: 'SEED-MTB-LENOVO-LGT5-G10',
      price: 31_490_000,
      category: catIds['may-tinh-bo'],
      totalStock: 10,
      description: 'Legion Ryzen + RTX 4060Ti, PSU 850W Platinum.',
      images: [img('https://p2-ofp.static.pub//fes/cms/2025/04/05/cg5n7n1yhqcen6h6st5zfjocfzncdb817997.jpg')],
      specifications: {
        cpuModel: 'AMD Ryzen 7 7700',
        gpuModel: 'NVIDIA GeForce RTX 4060 Ti 8GB',
        ram: '32GB DDR5',
        storage: '1TB NVMe SSD',
      },
    },

    // ══════════════════════════════════════════════════════════════════════════
    // MINI PC — 6
    // ══════════════════════════════════════════════════════════════════════════
    {
      name: 'Intel NUC 13 Pro Kit NUC13ANKi5',
      brand: 'Intel',
      sku: 'SEED-MPC-NUC13-ANKI5',
      price: 9_490_000,
      category: catIds['mini-pc'],
      totalStock: 15,
      description: 'Kit mini PC Barebone Intel 13 Gen, hỗ trợ DDR5 + M.2.',
      images: [img('https://m.media-amazon.com/images/I/51QeMJZeX8L._AC_UF894,1000_QL80_.jpg')],
      specifications: {
        formFactor: 'NUC Ultra Mini',
        ramSlots: '2× SO-DIMM DDR5',
        storage: '2× M.2 NVMe',
        tdpNote: '~28–65W (tùy CPU lắp)',
      },
    },
    {
      name: 'ASUS ExpertCenter PN65',
      brand: 'ASUS',
      sku: 'SEED-MPC-PN65',
      price: 12_490_000,
      category: catIds['mini-pc'],
      totalStock: 14,
      description: 'Mini PC Core Ultra AI — VGA tích hợp đổi mới không gian văn phòng.',
      images: [img('https://cdn-media.sforum.vn/storage/app/media/wp-content/uploads/2024/01/ASUS-ExpertCenter-PN65-cover.jpeg')],
      specifications: {
        processor: 'Intel Core Ultra 7',
        gpu: 'Intel Arc Graphics',
        ram: '32GB DDR5',
        storage: '1TB SSD',
      },
    },
    {
      name: 'Apple Mac mini M4',
      brand: 'Apple',
      sku: 'SEED-MPC-MAC-MINI-M4',
      price: 14_490_000,
      category: catIds['mini-pc'],
      totalStock: 20,
      description: 'Mac mini silicon M4 RAM 16GB, SSD có thể cấu hình.',
      images: [img('https://cdnv2.tgdd.vn/mwg-static/common/News/1571752/mac-mini-m4-1.jpg')],
      specifications: {
        chip: 'Apple M4',
        ram: '16GB Unified Memory',
        storage: '256GB SSD',
      },
    },
    {
      name: 'Lenovo ThinkCentre neo Ultra',
      brand: 'Lenovo',
      sku: 'SEED-MPC-TC-NEO-ULTRA',
      price: 16_990_000,
      category: catIds['mini-pc'],
      totalStock: 10,
      description: 'Ultra SFF workstation — PCIe cho GPU tí hon / AI.',
      images: [img('https://p1-ofp.static.pub//fes/cms/2024/06/03/i46nljylk7waopbm3tve8s0ay7cfl1933660.jpg')],
      specifications: {
        processor: 'Intel Core i7 Gen 13/14 tier',
        ram: '32GB DDR5',
        storage: '1TB SSD',
      },
    },
    {
      name: 'GEEKOM A8 Max Mini PC (Ryzen 9 AI)',
      brand: 'GEEKOM',
      sku: 'SEED-MPC-GEEKOM-A8MAX',
      price: 18_490_000,
      category: catIds['mini-pc'],
      totalStock: 12,
      description: 'Ryzen AI mini PC HDMI 4K quad — DDR5 + PCIe 4.0.',
      images: [img('https://m.media-amazon.com/images/I/71AwgG7YWyL.jpg')],
      specifications: {
        processor: 'AMD Ryzen AI 300 series',
        ram: '32GB DDR5',
        storage: '1TB SSD',
      },
    },
    {
      name: 'ASUS NUC 14 Performance NUC14RVSU',
      brand: 'ASUS',
      sku: 'SEED-MPC-NUC14-PERF',
      price: 22_990_000,
      category: catIds['mini-pc'],
      totalStock: 7,
      description: 'NUC 14 Pro with Core Ultra + Intel Arc — esports & stream.',
      images: [img('https://press.asus.com/assets/w_1372,h_913/589b2fb1-bcd1-40a7-8c9c-bcbc0f4e1cf3/ASUS%20NUC%2014%20Performance%20Press%20Photos.png')],
      specifications: {
        processor: 'Intel Core Ultra 9',
        gpu: 'Intel Arc Graphics',
        ram: '32GB DDR5',
        storage: '1TB SSD',
      },
    },
  ];
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error('❌  MONGODB_URI không tìm thấy trong .env!');
    process.exit(1);
  }

  console.log('🔌  Đang kết nối MongoDB Atlas...');
  await mongoose.connect(uri);
  console.log('✅  Kết nối thành công!\n');

  // 1. Upsert categories -------------------------------------------------------
  console.log('📂  Đang tạo / cập nhật danh mục...');
  const catIds: Record<string, mongoose.Types.ObjectId> = {};

  for (const cat of CATEGORIES) {
    const doc = await CategoryModel.findOneAndUpdate(
      { slug: cat.slug },
      { $set: cat },
      { upsert: true, new: true },
    );
    catIds[cat.slug] = doc!._id as mongoose.Types.ObjectId;
    console.log(`   ✔  ${cat.name} (${doc!._id})`);
  }

  // 2. Xoá sản phẩm seed cũ ---------------------------------------------------
  console.log('\n🗑   Xoá sản phẩm seed cũ (sku bắt đầu bằng "SEED-")...');
  const deleteResult = await ProductModel.deleteMany({
    sku: { $regex: /^SEED-/ },
  });
  console.log(`   Đã xoá ${deleteResult.deletedCount} sản phẩm cũ.`);

  // 3. Insert sản phẩm mới -----------------------------------------------------
  console.log('\n📦  Đang thêm sản phẩm mới...');
  const products = makeProducts(catIds);
  const inserted = await ProductModel.insertMany(products, { ordered: false });
  console.log(`   ✅  Đã thêm thành công ${inserted.length} sản phẩm!\n`);

  // 4. Summary -----------------------------------------------------------------
  const summary: Record<string, number> = {};
  for (const p of inserted as any[]) {
    const slug =
      Object.entries(catIds).find(([, id]) => id.equals(p.category))?.[0] ?? 'other';
    summary[slug] = (summary[slug] ?? 0) + 1;
  }
  console.log('📊  Tổng kết:');
  for (const [slug, count] of Object.entries(summary)) {
    console.log(`   ${slug.padEnd(12)} : ${count} sản phẩm`);
  }

  console.log(
    '\n💡  Ví dụ build tương thích (Intel DDR5):\n' +
    '   CPU      : Intel Core i9-14900K       (LGA1700, DDR5, 125W)\n' +
    '   Mainboard: ASUS ROG MAXIMUS Z790 Hero  (LGA1700, DDR5, ATX)\n' +
    '   RAM      : G.Skill Trident Z5 32GB    (DDR5 6000MHz)\n' +
    '   VGA      : RTX 4090 24GB              (336mm, 450W)\n' +
    '   PSU      : Corsair HX1000i 1000W      (≥ (125+20+6+450)*1.5 ✔)\n' +
    '   Cooler   : Noctua NH-D15              (165mm ≤ 167mm case ✔, 250W ≥ 125W ✔)\n' +
    '   Case     : Lian Li O11D EVO XL        (ATX ✔, GPU<420mm ✔, Cooler<167mm ✔)\n' +
    '   SSD      : Samsung 990 Pro 2TB\n',
  );

  await mongoose.disconnect();
  console.log('🔌  Đã ngắt kết nối. Seed hoàn tất!');
}

main().catch((err) => {
  console.error('❌  Seed thất bại:', err);
  process.exit(1);
});
