import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SiteLayout from "@/components/layouts/storefront/SiteLayout";
import { ToastContainer } from "react-toastify";
import { CartProvider } from "@/features/storefront/cart/context/CartContext";

import AuthProvider from "@/features/auth/components/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
      >
<AuthProvider>
          <CartProvider>
            <SiteLayout>
              {children}
            </SiteLayout>
          </CartProvider>
        </AuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
